/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as operations from "../operations/index.js";
import { ClientError } from "./clienterror.js";

/**
 * An error response object.
 */
export type GetProfileGoneHalJSONErrorData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.GetProfileGoneLinks;
};

/**
 * An error response object.
 */
export class GetProfileGoneHalJSONError extends ClientError {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.GetProfileGoneLinks;

  /** The original data that was passed to this error instance. */
  data$: GetProfileGoneHalJSONErrorData;

  constructor(
    err: GetProfileGoneHalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.title = err.title;
    this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    this.links = err.links;

    this.name = "GetProfileGoneHalJSONError";
  }
}

/**
 * An error response object.
 */
export type GetProfileNotFoundHalJSONErrorData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.GetProfileNotFoundLinks;
};

/**
 * An error response object.
 */
export class GetProfileNotFoundHalJSONError extends ClientError {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.GetProfileNotFoundLinks;

  /** The original data that was passed to this error instance. */
  data$: GetProfileNotFoundHalJSONErrorData;

  constructor(
    err: GetProfileNotFoundHalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.title = err.title;
    this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    this.links = err.links;

    this.name = "GetProfileNotFoundHalJSONError";
  }
}

/** @internal */
export const GetProfileGoneHalJSONError$inboundSchema: z.ZodType<
  GetProfileGoneHalJSONError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  title: z.string(),
  detail: z.string(),
  field: z.string().optional(),
  _links: z.lazy(() => operations.GetProfileGoneLinks$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new GetProfileGoneHalJSONError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetProfileGoneHalJSONError$Outbound = {
  status: number;
  title: string;
  detail: string;
  field?: string | undefined;
  _links: operations.GetProfileGoneLinks$Outbound;
};

/** @internal */
export const GetProfileGoneHalJSONError$outboundSchema: z.ZodType<
  GetProfileGoneHalJSONError$Outbound,
  z.ZodTypeDef,
  GetProfileGoneHalJSONError
> = z.instanceof(GetProfileGoneHalJSONError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int(),
      title: z.string(),
      detail: z.string(),
      field: z.string().optional(),
      links: z.lazy(() => operations.GetProfileGoneLinks$outboundSchema),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProfileGoneHalJSONError$ {
  /** @deprecated use `GetProfileGoneHalJSONError$inboundSchema` instead. */
  export const inboundSchema = GetProfileGoneHalJSONError$inboundSchema;
  /** @deprecated use `GetProfileGoneHalJSONError$outboundSchema` instead. */
  export const outboundSchema = GetProfileGoneHalJSONError$outboundSchema;
  /** @deprecated use `GetProfileGoneHalJSONError$Outbound` instead. */
  export type Outbound = GetProfileGoneHalJSONError$Outbound;
}

/** @internal */
export const GetProfileNotFoundHalJSONError$inboundSchema: z.ZodType<
  GetProfileNotFoundHalJSONError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  title: z.string(),
  detail: z.string(),
  field: z.string().optional(),
  _links: z.lazy(() => operations.GetProfileNotFoundLinks$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new GetProfileNotFoundHalJSONError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetProfileNotFoundHalJSONError$Outbound = {
  status: number;
  title: string;
  detail: string;
  field?: string | undefined;
  _links: operations.GetProfileNotFoundLinks$Outbound;
};

/** @internal */
export const GetProfileNotFoundHalJSONError$outboundSchema: z.ZodType<
  GetProfileNotFoundHalJSONError$Outbound,
  z.ZodTypeDef,
  GetProfileNotFoundHalJSONError
> = z.instanceof(GetProfileNotFoundHalJSONError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int(),
      title: z.string(),
      detail: z.string(),
      field: z.string().optional(),
      links: z.lazy(() => operations.GetProfileNotFoundLinks$outboundSchema),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProfileNotFoundHalJSONError$ {
  /** @deprecated use `GetProfileNotFoundHalJSONError$inboundSchema` instead. */
  export const inboundSchema = GetProfileNotFoundHalJSONError$inboundSchema;
  /** @deprecated use `GetProfileNotFoundHalJSONError$outboundSchema` instead. */
  export const outboundSchema = GetProfileNotFoundHalJSONError$outboundSchema;
  /** @deprecated use `GetProfileNotFoundHalJSONError$Outbound` instead. */
  export type Outbound = GetProfileNotFoundHalJSONError$Outbound;
}
