/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as operations from "../operations/index.js";
import { ClientError } from "./clienterror.js";

/**
 * An error response object.
 */
export type ListRefundsNotFoundHalJSONErrorData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
   *
   * @remarks
   * of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.ListRefundsNotFoundLinks;
};

/**
 * An error response object.
 */
export class ListRefundsNotFoundHalJSONError extends ClientError {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
   *
   * @remarks
   * of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.ListRefundsNotFoundLinks;

  /** The original data that was passed to this error instance. */
  data$: ListRefundsNotFoundHalJSONErrorData;

  constructor(
    err: ListRefundsNotFoundHalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.title = err.title;
    this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    this.links = err.links;

    this.name = "ListRefundsNotFoundHalJSONError";
  }
}

/**
 * An error response object.
 */
export type ListRefundsBadRequestHalJSONErrorData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
   *
   * @remarks
   * of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.ListRefundsBadRequestLinks;
};

/**
 * An error response object.
 */
export class ListRefundsBadRequestHalJSONError extends ClientError {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
   *
   * @remarks
   * of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.ListRefundsBadRequestLinks;

  /** The original data that was passed to this error instance. */
  data$: ListRefundsBadRequestHalJSONErrorData;

  constructor(
    err: ListRefundsBadRequestHalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.title = err.title;
    this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    this.links = err.links;

    this.name = "ListRefundsBadRequestHalJSONError";
  }
}

/** @internal */
export const ListRefundsNotFoundHalJSONError$inboundSchema: z.ZodType<
  ListRefundsNotFoundHalJSONError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  title: z.string(),
  detail: z.string(),
  field: z.string().optional(),
  _links: z.lazy(() => operations.ListRefundsNotFoundLinks$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new ListRefundsNotFoundHalJSONError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ListRefundsNotFoundHalJSONError$Outbound = {
  status: number;
  title: string;
  detail: string;
  field?: string | undefined;
  _links: operations.ListRefundsNotFoundLinks$Outbound;
};

/** @internal */
export const ListRefundsNotFoundHalJSONError$outboundSchema: z.ZodType<
  ListRefundsNotFoundHalJSONError$Outbound,
  z.ZodTypeDef,
  ListRefundsNotFoundHalJSONError
> = z.instanceof(ListRefundsNotFoundHalJSONError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int(),
      title: z.string(),
      detail: z.string(),
      field: z.string().optional(),
      links: z.lazy(() => operations.ListRefundsNotFoundLinks$outboundSchema),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRefundsNotFoundHalJSONError$ {
  /** @deprecated use `ListRefundsNotFoundHalJSONError$inboundSchema` instead. */
  export const inboundSchema = ListRefundsNotFoundHalJSONError$inboundSchema;
  /** @deprecated use `ListRefundsNotFoundHalJSONError$outboundSchema` instead. */
  export const outboundSchema = ListRefundsNotFoundHalJSONError$outboundSchema;
  /** @deprecated use `ListRefundsNotFoundHalJSONError$Outbound` instead. */
  export type Outbound = ListRefundsNotFoundHalJSONError$Outbound;
}

/** @internal */
export const ListRefundsBadRequestHalJSONError$inboundSchema: z.ZodType<
  ListRefundsBadRequestHalJSONError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  title: z.string(),
  detail: z.string(),
  field: z.string().optional(),
  _links: z.lazy(() => operations.ListRefundsBadRequestLinks$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new ListRefundsBadRequestHalJSONError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ListRefundsBadRequestHalJSONError$Outbound = {
  status: number;
  title: string;
  detail: string;
  field?: string | undefined;
  _links: operations.ListRefundsBadRequestLinks$Outbound;
};

/** @internal */
export const ListRefundsBadRequestHalJSONError$outboundSchema: z.ZodType<
  ListRefundsBadRequestHalJSONError$Outbound,
  z.ZodTypeDef,
  ListRefundsBadRequestHalJSONError
> = z.instanceof(ListRefundsBadRequestHalJSONError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int(),
      title: z.string(),
      detail: z.string(),
      field: z.string().optional(),
      links: z.lazy(() => operations.ListRefundsBadRequestLinks$outboundSchema),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRefundsBadRequestHalJSONError$ {
  /** @deprecated use `ListRefundsBadRequestHalJSONError$inboundSchema` instead. */
  export const inboundSchema = ListRefundsBadRequestHalJSONError$inboundSchema;
  /** @deprecated use `ListRefundsBadRequestHalJSONError$outboundSchema` instead. */
  export const outboundSchema =
    ListRefundsBadRequestHalJSONError$outboundSchema;
  /** @deprecated use `ListRefundsBadRequestHalJSONError$Outbound` instead. */
  export type Outbound = ListRefundsBadRequestHalJSONError$Outbound;
}
