/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as operations from "../operations/index.js";
import { ClientError } from "./clienterror.js";

/**
 * An error response object.
 */
export type UpdatePaymentLinkUnprocessableEntityHalJSONErrorData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
   *
   * @remarks
   * of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.UpdatePaymentLinkUnprocessableEntityLinks;
};

/**
 * An error response object.
 */
export class UpdatePaymentLinkUnprocessableEntityHalJSONError
  extends ClientError
{
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
   *
   * @remarks
   * of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.UpdatePaymentLinkUnprocessableEntityLinks;

  /** The original data that was passed to this error instance. */
  data$: UpdatePaymentLinkUnprocessableEntityHalJSONErrorData;

  constructor(
    err: UpdatePaymentLinkUnprocessableEntityHalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.title = err.title;
    this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    this.links = err.links;

    this.name = "UpdatePaymentLinkUnprocessableEntityHalJSONError";
  }
}

/**
 * An error response object.
 */
export type UpdatePaymentLinkNotFoundHalJSONErrorData = {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
   *
   * @remarks
   * of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.UpdatePaymentLinkNotFoundLinks;
};

/**
 * An error response object.
 */
export class UpdatePaymentLinkNotFoundHalJSONError extends ClientError {
  /**
   * The status code of the error message. This is always the same code as the status code of the HTTP message itself.
   */
  status: number;
  /**
   * The HTTP reason phrase of the error. For example, for a `404` error, the `title` will be `Not Found`.
   */
  title: string;
  /**
   * A detailed human-readable description of the error that occurred.
   */
  detail: string;
  /**
   * If the error was caused by a value provided by you in a specific field, the `field` property will contain the name
   *
   * @remarks
   * of the field that caused the issue.
   */
  field?: string | undefined;
  links: operations.UpdatePaymentLinkNotFoundLinks;

  /** The original data that was passed to this error instance. */
  data$: UpdatePaymentLinkNotFoundHalJSONErrorData;

  constructor(
    err: UpdatePaymentLinkNotFoundHalJSONErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;
    this.title = err.title;
    this.detail = err.detail;
    if (err.field != null) this.field = err.field;
    this.links = err.links;

    this.name = "UpdatePaymentLinkNotFoundHalJSONError";
  }
}

/** @internal */
export const UpdatePaymentLinkUnprocessableEntityHalJSONError$inboundSchema:
  z.ZodType<
    UpdatePaymentLinkUnprocessableEntityHalJSONError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status: z.number().int(),
    title: z.string(),
    detail: z.string(),
    field: z.string().optional(),
    _links: z.lazy(() =>
      operations.UpdatePaymentLinkUnprocessableEntityLinks$inboundSchema
    ),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "_links": "links",
      });

      return new UpdatePaymentLinkUnprocessableEntityHalJSONError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type UpdatePaymentLinkUnprocessableEntityHalJSONError$Outbound = {
  status: number;
  title: string;
  detail: string;
  field?: string | undefined;
  _links: operations.UpdatePaymentLinkUnprocessableEntityLinks$Outbound;
};

/** @internal */
export const UpdatePaymentLinkUnprocessableEntityHalJSONError$outboundSchema:
  z.ZodType<
    UpdatePaymentLinkUnprocessableEntityHalJSONError$Outbound,
    z.ZodTypeDef,
    UpdatePaymentLinkUnprocessableEntityHalJSONError
  > = z.instanceof(UpdatePaymentLinkUnprocessableEntityHalJSONError)
    .transform(v => v.data$)
    .pipe(
      z.object({
        status: z.number().int(),
        title: z.string(),
        detail: z.string(),
        field: z.string().optional(),
        links: z.lazy(() =>
          operations.UpdatePaymentLinkUnprocessableEntityLinks$outboundSchema
        ),
      }).transform((v) => {
        return remap$(v, {
          links: "_links",
        });
      }),
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePaymentLinkUnprocessableEntityHalJSONError$ {
  /** @deprecated use `UpdatePaymentLinkUnprocessableEntityHalJSONError$inboundSchema` instead. */
  export const inboundSchema =
    UpdatePaymentLinkUnprocessableEntityHalJSONError$inboundSchema;
  /** @deprecated use `UpdatePaymentLinkUnprocessableEntityHalJSONError$outboundSchema` instead. */
  export const outboundSchema =
    UpdatePaymentLinkUnprocessableEntityHalJSONError$outboundSchema;
  /** @deprecated use `UpdatePaymentLinkUnprocessableEntityHalJSONError$Outbound` instead. */
  export type Outbound =
    UpdatePaymentLinkUnprocessableEntityHalJSONError$Outbound;
}

/** @internal */
export const UpdatePaymentLinkNotFoundHalJSONError$inboundSchema: z.ZodType<
  UpdatePaymentLinkNotFoundHalJSONError,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  title: z.string(),
  detail: z.string(),
  field: z.string().optional(),
  _links: z.lazy(() => operations.UpdatePaymentLinkNotFoundLinks$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "_links": "links",
    });

    return new UpdatePaymentLinkNotFoundHalJSONError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UpdatePaymentLinkNotFoundHalJSONError$Outbound = {
  status: number;
  title: string;
  detail: string;
  field?: string | undefined;
  _links: operations.UpdatePaymentLinkNotFoundLinks$Outbound;
};

/** @internal */
export const UpdatePaymentLinkNotFoundHalJSONError$outboundSchema: z.ZodType<
  UpdatePaymentLinkNotFoundHalJSONError$Outbound,
  z.ZodTypeDef,
  UpdatePaymentLinkNotFoundHalJSONError
> = z.instanceof(UpdatePaymentLinkNotFoundHalJSONError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      status: z.number().int(),
      title: z.string(),
      detail: z.string(),
      field: z.string().optional(),
      links: z.lazy(() =>
        operations.UpdatePaymentLinkNotFoundLinks$outboundSchema
      ),
    }).transform((v) => {
      return remap$(v, {
        links: "_links",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePaymentLinkNotFoundHalJSONError$ {
  /** @deprecated use `UpdatePaymentLinkNotFoundHalJSONError$inboundSchema` instead. */
  export const inboundSchema =
    UpdatePaymentLinkNotFoundHalJSONError$inboundSchema;
  /** @deprecated use `UpdatePaymentLinkNotFoundHalJSONError$outboundSchema` instead. */
  export const outboundSchema =
    UpdatePaymentLinkNotFoundHalJSONError$outboundSchema;
  /** @deprecated use `UpdatePaymentLinkNotFoundHalJSONError$Outbound` instead. */
  export type Outbound = UpdatePaymentLinkNotFoundHalJSONError$Outbound;
}
