/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { balancesList } from "../../funcs/balancesList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListBalancesRequest$inboundSchema.optional(),
};

export const tool$balancesList: ToolDefinition<typeof args> = {
  name: "balances-list",
  description: `List balances

Retrieve a list of the organization's balances, including the primary balance.

The results are paginated.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await balancesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
