/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { settlementsListCaptures } from "../../funcs/settlementsListCaptures.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetSettlementCapturesRequest$inboundSchema,
};

export const tool$settlementsListCaptures: ToolDefinition<typeof args> = {
  name: "settlements-list-captures",
  description: `Get settlement captures

Retrieve all captures included in the given settlement.

The response is in the same format as the response of the [List captures endpoint](list-captures).

> 🔑 Access with
>
> [Access token with **settlements.read** **payments.read**](/reference/authentication)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await settlementsListCaptures(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
