/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { settlementsListChargebacks } from "../../funcs/settlementsListChargebacks.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListSettlementChargebacksRequest$inboundSchema,
};

export const tool$settlementsListChargebacks: ToolDefinition<typeof args> = {
  name: "settlements-list-chargebacks",
  description: `List settlement chargebacks

Retrieve all chargebacks 'deducted' from the given settlement.

The response is in the same format as the response of the [List chargebacks endpoint](list-chargebacks).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await settlementsListChargebacks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
