/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksTest } from "../../funcs/webhooksTest.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.TestWebhookRequest$inboundSchema,
};

export const tool$webhooksTest: ToolDefinition<typeof args> = {
  name: "webhooks-test",
  description: `Test a webhook

Sends a test event to the webhook to verify the endpoint is working as expected.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksTest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
