openapi: 3.1.0
info:
  title: Mollie API
  version: 1.0.0
  license:
    name: Attribution-NonCommercial-ShareAlike 4.0 International
    identifier: CC-BY-NC-SA-4.0
servers:
  - url: https://api.mollie.com/v2
security:
  - apiKey: []
  - oAuth: []
tags:
  - name: Balances API
    description: Operations related to the Balances API
  - name: Capabilities API
    description: Operations related to the Capabilities API
  - name: Captures API
    description: Operations related to the Captures API
  - name: Chargebacks API
    description: Operations related to the Chargebacks API
  - name: Client Links API
    description: Operations related to the Client Links API
  - name: Clients API
    description: Operations related to the Clients API
  - name: Customers API
    description: Operations related to the Customers API
  - name: Delayed Routing API
    description: Operations related to the Delayed Routing API
  - name: Invoices API
    description: Operations related to the Invoices API
  - name: Mandates API
    description: Operations related to the Mandates API
  - name: Methods API
    description: Operations related to the Methods API
  - name: Onboarding API
    description: Operations related to the Onboarding API
  - name: Organizations API
    description: Operations related to the Organizations API
  - name: Payment Links API
    description: Operations related to the Payment Links API
  - name: Payments API
    description: Operations related to the Payments API
  - name: Permissions API
    description: Operations related to the Permissions API
  - name: Profiles API
    description: Operations related to the Profiles API
  - name: Refunds API
    description: Operations related to the Refunds API
  - name: Sales Invoices API
    description: Operations related to the Sales Invoices API
  - name: Settlements API
    description: Operations related to the Settlements API
  - name: Subscriptions API
    description: Operations related to the Subscriptions API
  - name: Terminals API
    description: Operations related to the Terminals API
  - name: Wallets API
    description: Operations related to the Wallets API
  - name: Webhook Events API
    description: Operations related to the Webhook Events API
  - name: Webhooks API
    description: Operations related to the Webhooks API
paths:
  /balances:
    get:
      summary: List balances
      tags:
        - Balances API
      operationId: list-balances
      security:
        - oAuth:
            - balances.read
      description: |-
        Retrieve a list of the organization's balances, including the primary balance.

        The results are paginated.
  /balances/{id}:
    get:
      summary: Get balance
      tags:
        - Balances API
      operationId: get-balance
      security:
        - oAuth:
            - balances.read
      description: |-
        When processing payments with Mollie, we put all pending funds — usually
        minus Mollie fees — on a balance. Once you have linked a bank account to your Mollie account, we can pay out your
        balance towards this bank account.

        With the Balances API you can retrieve your current balance. The response
        includes two amounts:

        * The *pending amount*. These are payments that have been marked as `paid`,
        but are not yet available on your balance.
        * The *available amount*. This is the amount that you can get paid out to
        your bank account, or use for refunds.

        With instant payment methods like iDEAL, payments are moved to the available
        balance instantly. With slower payment methods, like credit card for example, it can take a few days before the
        funds are available on your balance. These funds will be shown under the *pending amount* in the meanwhile.
  /balances/primary:
    get:
      summary: Get primary balance
      tags:
        - Balances API
      operationId: get-primary-balance
      security:
        - oAuth:
            - balances.read
      description: |-
        Retrieve the primary balance. This is the balance of your account's primary
        currency, where all payments are settled to by default.

        This endpoint is a convenient alias of the [Get balance](get-balance)
        endpoint.
  /balances/{balanceId}/report:
    get:
      summary: Get balance report
      tags:
        - Balances API
      operationId: get-balance-report
      security:
        - oAuth:
            - balance-reports.read
      description: |-
        Retrieve a summarized report for all transactions on a given balance within a given timeframe.

        The API also provides a detailed report on all 'prepayments' for Mollie fees that were deducted from your balance
        during the reported period, ahead of your Mollie invoice.

        The alias `primary` can be used instead of the balance ID to refer to the
        organization's primary balance.
  /balances/{balanceId}/transactions:
    get:
      summary: List balance transactions
      tags:
        - Balances API
      operationId: list-balance-transactions
      security:
        - oAuth:
            - balances.read
      description: |-
        Retrieve a list of all balance transactions. Transactions include for
        example payments, refunds, chargebacks, and settlements.

        For an aggregated report of these balance transactions, refer to the [Get
        balance report](get-balance-report) endpoint.

        The alias `primary` can be used instead of the balance ID to refer to the
        organization's primary balance.

        The results are paginated.
  /settlements:
    get:
      summary: List settlements
      tags:
        - Settlements API
      operationId: list-settlements
      security:
        - oAuth:
            - settlements.read
      description: |-
        Retrieve a list of all your settlements.

        The results are paginated.
  /settlements/{id}:
    get:
      summary: Get settlement
      tags:
        - Settlements API
      operationId: get-settlement
      security:
        - oAuth:
            - settlements.read
      description: |-
        Retrieve a single settlement by its ID.

        To lookup settlements by their bank reference, replace the ID in the URL by
        a reference. For example: `1234567.2404.03`.

        A settlement represents a transfer of your balance funds to your external bank account.

        Settlements will typically include a report that details what balance transactions have taken place between this
        settlement and the previous one.

        For more accurate bookkeeping, refer to the [balance report](get-balance-report) endpoint or the
        [balance transactions](list-balance-transactions) endpoint.
  /settlements/open:
    get:
      summary: Get open settlement
      tags:
        - Settlements API
      operationId: get-open-settlement
      security:
        - oAuth:
            - settlements.read
      description: |-
        Retrieve the details of the open balance of the organization. This will return a settlement object representing your
        organization's balance.

        For a complete reference of the settlement object, refer to the [Get settlement endpoint](get-settlement)
        documentation.

        For more accurate bookkeeping, refer to the [balance report](get-balance-report) endpoint or the
        [balance transactions](list-balance-transactions) endpoint.
  /settlements/next:
    get:
      summary: Get next settlement
      tags:
        - Settlements API
      operationId: get-next-settlement
      security:
        - oAuth:
            - settlements.read
      description: |-
        Retrieve the details of the current settlement, that has not yet been paid out.

        For a complete reference of the settlement object, refer to the [Get settlement endpoint](get-settlement)
        documentation.

        For more accurate bookkeeping, refer to the [balance report](get-balance-report) endpoint or the
        [balance transactions](list-balance-transactions) endpoint.
  /settlements/{settlementId}/payments:
    get:
      summary: List settlement payments
      tags:
        - Settlements API
      operationId: list-settlement-payments
      security:
        - oAuth:
            - settlements.read
            - payments.read
      description: |-
        Retrieve all payments included in the given settlement.

        The response is in the same format as the response of the [List payments endpoint](list-payments).

        For capture-based payment methods such as Klarna, the payments are not listed here. Refer to the
        [List captures endpoint](list-captures) endpoint instead.
  /settlements/{settlementId}/captures:
    get:
      summary: List settlement captures
      tags:
        - Settlements API
      operationId: list-settlement-captures
      security:
        - oAuth:
            - settlements.read
            - payments.read
      description: |-
        Retrieve all captures included in the given settlement.

        The response is in the same format as the response of the [List captures endpoint](list-captures).
  /settlements/{settlementId}/refunds:
    get:
      summary: List settlement refunds
      tags:
        - Settlements API
      operationId: list-settlement-refunds
      security:
        - oAuth:
            - settlements.read
            - refunds.read
      description: |-
        Retrieve all refunds 'deducted' from the given settlement.

        The response is in the same format as the response of the [List refunds endpoint](list-refunds).
  /settlements/{settlementId}/chargebacks:
    get:
      summary: List settlement chargebacks
      tags:
        - Settlements API
      operationId: list-settlement-chargebacks
      security:
        - oAuth:
            - settlements.read
            - payments.read
      description: |-
        Retrieve all chargebacks 'deducted' from the given settlement.

        The response is in the same format as the response of the [List chargebacks endpoint](list-chargebacks).
  /invoices:
    get:
      summary: List invoices
      tags:
        - Invoices API
      operationId: list-invoices
      security:
        - oAuth:
            - invoices.read
      description: |-
        Retrieve a list of all your invoices, optionally filtered by year or by
        invoice reference.

        The results are paginated.
  /invoices/{id}:
    get:
      summary: Get invoice
      tags:
        - Invoices API
      operationId: get-invoice
      security:
        - oAuth:
            - invoices.read
      description: |-
        Retrieve a single invoice by its ID.

        If you want to retrieve the details of an invoice by its invoice number,
        call the [List invoices](list-invoices) endpoint with the `reference` parameter.
  /permissions:
    get:
      summary: List permissions
      tags:
        - Permissions API
      operationId: list-permissions
      security:
        - oAuth: []
      description: |-
        Retrieve a list of all permissions available to the current access token.

        The results are **not** paginated.
  /permissions/{permissionId}:
    get:
      summary: Get permission
      tags:
        - Permissions API
      operationId: get-permission
      security:
        - oAuth: []
      description: Retrieve a single permission by its ID, and see if the permission is granted to the current access token.
  /organizations/{id}:
    get:
      summary: Get organization
      tags:
        - Organizations API
      operationId: get-organization
      security:
        - oAuth:
            - organizations.read
      description: |-
        Retrieve a single organization by its ID.

        You can normally only retrieve the currently authenticated organization with this endpoint. This is primarily useful
        for OAuth apps. See also [Get current organization](get-current-organization).

        If you have a *partner account*', you can retrieve organization details of connected organizations.
  /organizations/me:
    get:
      summary: Get current organization
      tags:
        - Organizations API
      operationId: get-current-organization
      security:
        - oAuth:
            - organizations.read
      description: |-
        Retrieve the currently authenticated organization. A convenient alias of the [Get organization](get-organization)
        endpoint.

        For a complete reference of the organization object, refer to the [Get organization](get-organization) endpoint
        documentation.
  /organizations/me/partner:
    get:
      summary: Get partner status
      tags:
        - Organizations API
      operationId: get-partner-status
      security:
        - oAuth:
            - organizations.read
      description: |-
        Retrieve partnership details about the currently authenticated organization. Only relevant for so-called *partner
        accounts*.
  /profiles:
    post:
      summary: Create profile
      tags:
        - Profiles API
      operationId: create-profile
      security:
        - oAuth:
            - profiles.write
      description: |-
        Create a profile to process payments on.

        Profiles are required for payment processing. Normally they are created via the Mollie dashboard. Alternatively, you
        can use this endpoint to automate profile creation.
    get:
      summary: List profiles
      tags:
        - Profiles API
      operationId: list-profiles
      security:
        - oAuth:
            - profiles.read
      description: |-
        Retrieve a list of all of your profiles.

        The results are paginated.
  /profiles/{id}:
    get:
      summary: Get profile
      tags:
        - Profiles API
      operationId: get-profile
      security:
        - oAuth:
            - profiles.read
      description: Retrieve a single profile by its ID.
    patch:
      summary: Update profile
      tags:
        - Profiles API
      operationId: update-profile
      security:
        - oAuth:
            - profiles.write
      description: |-
        Update an existing profile.

        Profiles are required for payment processing. Normally they are created and updated via the Mollie dashboard.
        Alternatively, you can use this endpoint to automate profile management.
    delete:
      summary: Delete profile
      tags:
        - Profiles API
      operationId: delete-profile
      security:
        - oAuth:
            - profiles.write
      description: Delete a profile. A deleted profile and its related credentials can no longer be used for accepting payments.
  /profiles/me:
    get:
      summary: Get current profile
      tags:
        - Profiles API
      operationId: get-current-profile
      security:
        - apiKey: []
      description: |-
        Retrieve the currently authenticated profile. A convenient alias of the [Get profile](get-profile)
        endpoint.

        For a complete reference of the profile object, refer to the [Get profile](get-profile) endpoint
        documentation.
  /onboarding/me:
    get:
      summary: Get onboarding status
      tags:
        - Onboarding API
      operationId: get-onboarding-status
      security:
        - oAuth:
            - onboarding.read
      description: Retrieve the onboarding status of the currently authenticated organization.
    post:
      summary: Submit onboarding data
      tags:
        - Onboarding API
      operationId: submit-onboarding-data
      security:
        - oAuth:
            - onboarding.write
      description: |-
        **⚠️ We no longer recommend implementing this endpoint. Please refer to the Client Links API instead to kick off the
        onboarding process for your merchants.**

        Submit data that will be prefilled in the merchant's onboarding. The data you submit will only be processed when the
        onboarding status is `needs-data`.  
        Information that the merchant has entered in their dashboard will not be overwritten.
  /capabilities:
    get:
      summary: List capabilities
      tags:
        - Capabilities API
      operationId: list-capabilities
      security:
        - oAuth:
            - onboarding.read
      description: |-
        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Retrieve a list of capabilities for an organization.

        This API provides detailed insights into the specific requirements and status of each client's onboarding journey.

        Capabilities are at the organization level, indicating if the organization can perform a given capability.

        For payments, regardless them being at the profile level, the capability is listed at the organization level.
        This means that if at least one of the clients's profiles can receive payments,
        the payments capability is enabled, communicating that the organization can indeed receive payments.
  /clients:
    get:
      summary: List clients
      tags:
        - Clients API
      operationId: list-clients
      security:
        - oAuth:
            - clients.read
      description: |-
        Retrieve a list of all clients linked to your account.

        The results are paginated.
  /clients/{id}:
    get:
      summary: Get client
      tags:
        - Clients API
      operationId: get-client
      security:
        - oAuth:
            - clients.read
      description: Retrieve a single client by its ID.
  /client-links:
    post:
      summary: Create client link
      tags:
        - Client Links API
      operationId: create-client-link
      security:
        - oAuth:
            - clients.write
      description: |-
        Link a new or existing organization to your OAuth application, in effect creating a new client. The response
        contains a `clientLink` where you should redirect your customer to.

        ## Redirecting the Customer

        The `clientLink` URL behaves similarly to a standard OAuth authorization URL. Therefore, after receiving the
        `clientLink` URL in the API response, you need to **append the following query parameters** *before* redirecting
        the customer:

        * `client_id` _string (required)_

          The client ID you received when you registered your OAuth app. The ID starts with `app_`. For example:
          `app_abc123qwerty`.

        * `state` _string (required)_

          A random string **generated by your app** to prevent CSRF attacks. This will be reflected in the `state` query
          parameter when the user returns to the `redirect_uri` after authorizing your app.

        * `scope` _string (required)_

          A space-separated list of permissions ('scopes') your app requires. See the
          [permissions list](https://docs.mollie.com/docs/connect-permissions) for more information about the available
          scopes.

          We recommend at least : `onboarding.read onboarding.write`

        * `approval_prompt` _string_

          Can be set to `force` to force showing the consent screen to the merchant, *even when it is not necessary*. If you
          force an approval prompt and the user creates a new authorization, previously active authorizations will be
          revoked.

          Possible values: `auto` `force` (default: `auto`)

        ### Example of a Complete Redirect URL

        After adding the above url parameter your URL will look something like this and you can redirect your client to this
        page:

        ```
        https://my.mollie.com/dashboard/client-link/{id}?client_id={your_client_id}&state={unique_state}&scope=onboarding.read%20onboarding.write
        ```

        ## Error Handling

        Error handling is also dealt with similar to the [Authorize](https://docs.mollie.com/reference/authorize) endpoint:
        the customer is redirected back to your app's redirect URL with the `error` and `error_description` parameters added
        to the URL.

        > 🚧
        >
        > A client link must be used within 30 days of creation. After that period, it will expire and you will need to create a new client link.
  /webhooks:
    post:
      summary: Create a webhook
      tags:
        - Webhooks API
      operationId: create-webhook
      security:
        - oAuth:
            - webhooks.write
      description: A webhook must have a name, an url and a list of event types. You can also create webhooks in the webhooks settings section of the Dashboard.
    get:
      summary: List all webhooks
      tags:
        - Webhooks API
      operationId: list-webhooks
      security:
        - oAuth:
            - webhooks.read
      description: Returns a paginated list of your webhooks. If no webhook endpoints are available, the resulting array will be empty. This request should never throw an error.
  /webhooks/{id}:
    patch:
      summary: Update a webhook
      tags:
        - Webhooks API
      operationId: update-webhook
      security:
        - oAuth:
            - webhooks.write
      description: Updates the webhook. You may edit the name, url and the list of subscribed event types.
    get:
      summary: Get a webhook
      tags:
        - Webhooks API
      operationId: get-webhook
      security:
        - oAuth:
            - webhooks.read
      description: Retrieve a single webhook object by its ID.
    delete:
      summary: Delete a webhook
      tags:
        - Webhooks API
      operationId: delete-webhook
      security:
        - oAuth:
            - webhooks.write
      description: Delete a single webhook object by its webhook ID.
  /webhooks/{id}/ping:
    post:
      summary: Test a webhook
      tags:
        - Webhooks API
      operationId: test-webhook
      security:
        - oAuth:
            - webhooks.write
      description: Sends a test event to the webhook to verify the endpoint is working as expected.
  /events/{id}:
    get:
      summary: Get a Webhook Event
      tags:
        - Webhook Events API
      operationId: get-webhook-event
      security:
        - oAuth:
            - events.read
      description: Retrieve a single webhook event object by its event ID.
  /payments:
    post:
      summary: Create payment
      tags:
        - Payments API
      operationId: create-payment
      security:
        - apiKey: []
        - oAuth:
            - payments.write
      description: |-
        Payment creation is elemental to the Mollie API: this is where most payment
        implementations start off.

        Once you have created a payment, you should redirect your customer to the
        URL in the `_links.checkout` property from the response.

        To wrap your head around the payment process, an explanation and flow charts
        can be found in the 'Accepting payments' guide.

        If you specify the `method` parameter when creating a payment, optional
        additional parameters may be available for the payment method that are not listed below. Please refer to the
        guide on [method-specific parameters](extra-payment-parameters).
    get:
      summary: List payments
      tags:
        - Payments API
      operationId: list-payments
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: |-
        Retrieve all payments created with the current website profile.

        The results are paginated.
  /payments/{paymentId}:
    get:
      summary: Get payment
      tags:
        - Payments API
      operationId: get-payment
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: Retrieve a single payment object by its payment ID.
    patch:
      summary: Update payment
      tags:
        - Payments API
      operationId: update-payment
      security:
        - apiKey: []
        - oAuth:
            - payments.write
      description: |-
        Certain details of an existing payment can be updated.

        Updating the payment details will not result in a webhook call.
    delete:
      summary: Cancel payment
      tags:
        - Payments API
      operationId: cancel-payment
      security:
        - apiKey: []
        - oAuth:
            - payments.write
      description: |-
        Depending on the payment method, you may be able to cancel a payment for a certain amount of time — usually until
        the next business day or as long as the payment status is open.

        Payments may also be canceled manually from the Mollie Dashboard.

        The `isCancelable` property on the [Payment object](get-payment) will indicate if the payment can be canceled.
  /payments/{paymentId}/release-authorization:
    post:
      summary: Release payment authorization
      tags:
        - Payments API
      operationId: release-authorization
      security:
        - apiKey: []
        - oAuth:
            - payments.write
      description: |-
        Releases the full remaining authorized amount. Call this endpoint when you will not be making any additional
        captures. Payment authorizations may also be released manually from the Mollie Dashboard.

        Mollie will do its best to process release requests, but it is not guaranteed that it will succeed. It is up to
        the issuing bank if and when the hold will be released.

        If the request does succeed, the payment status will change to `canceled` for payments without captures.
        If there is a successful capture, the payment will transition to `paid`.
  /methods:
    get:
      summary: List payment methods
      tags:
        - Methods API
      operationId: list-methods
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: |-
        Retrieve all enabled payment methods. The results of this endpoint are
        **not** paginated — unlike most other list endpoints in our API.

        For test mode, all pending and enabled payment methods are returned. If no
        payment methods are requested yet, the most popular payment methods are returned in the test mode. For live
        mode, only fully enabled payment methods are returned.

        Payment methods can be requested and enabled via the Mollie Dashboard, or
        via the [Enable payment method endpoint](enable-method) of the Profiles API.

        The list can optionally be filtered using a number of parameters described
        below.

        By default, only payment methods for the Euro currency are returned. If you
        wish to retrieve payment methods which exclusively support other currencies (e.g. Twint), you need to use the
        `amount` parameters.
  /methods/all:
    get:
      summary: List all payment methods
      tags:
        - Methods API
      operationId: list-all-methods
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: |-
        Retrieve all payment methods that Mollie offers, regardless of the eligibility of the organization for the specific
        method. The results of this endpoint are **not** paginated — unlike most other list endpoints in our API.

        The list can optionally be filtered using a number of parameters described below.
  /methods/{id}:
    get:
      summary: Get payment method
      tags:
        - Methods API
      operationId: get-method
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: |-
        Retrieve a single payment method by its ID.

        If a method is not available on this profile, a `404 Not Found` response is
        returned. If the method is available but not enabled yet, a status `403 Forbidden` is returned. You can enable
        payments methods via the [Enable payment method endpoint](enable-method) of the Profiles API, or via
        the Mollie Dashboard.

        If you do not know the method's ID, you can use the [methods list
        endpoint](list-methods) to retrieve all payment methods that are available.

        Additionally, it is possible to check if wallet methods such as Apple Pay
        are enabled by passing the wallet ID (`applepay`) as the method ID.
  /profiles/{profileId}/methods/{id}:
    post:
      summary: Enable payment method
      tags:
        - Methods API
      operationId: enable-method
      security:
        - apiKey: []
        - oAuth:
            - profiles.write
      description: |-
        Enable a payment method on a specific profile.

        When using a profile-specific API credential, the alias `me` can be used
        instead of the profile ID to refer to the current profile.

        Some payment methods require extra steps in order to be activated. In cases
        where a step at the payment method provider needs to be completed first, the status will be set to
        `pending-external` and the response will contain a link to complete the activation at the provider.

        To enable voucher or gift card issuers, refer to the [Enable payment method issuer](enable-method-issuer) endpoint.
    delete:
      summary: Disable payment method
      tags:
        - Methods API
      operationId: disable-method
      security:
        - apiKey: []
        - oAuth:
            - profiles.write
      description: |-
        Disable a payment method on a specific profile.

        When using a profile-specific API credential, the alias `me` can be used
        instead of the profile ID to refer to the current profile.
  /profiles/{profileId}/methods/{methodId}/issuers/{id}:
    post:
      summary: Enable payment method issuer
      tags:
        - Methods API
      operationId: enable-method-issuer
      security:
        - apiKey: []
        - oAuth:
            - profiles.write
      description: |-
        Enable an issuer for a payment method on a specific profile.

        Currently only the payment methods `voucher` and `giftcard` are supported.

        When using a profile-specific API credential, the alias `me` can be used instead of the profile ID to refer to the
        current profile.
    delete:
      summary: Disable payment method issuer
      tags:
        - Methods API
      operationId: disable-method-issuer
      security:
        - apiKey: []
        - oAuth:
            - profiles.write
      description: |-
        Disable an issuer for a payment method on a specific profile.

        Currently only the payment methods `voucher` and `giftcard` are supported.

        When using a profile-specific API credential, the alias `me` can be used instead of the profile ID to refer to the
        current profile.
  /payments/{paymentId}/refunds:
    post:
      summary: Create payment refund
      tags:
        - Refunds API
      operationId: create-refund
      security:
        - apiKey: []
        - oAuth:
            - refunds.write
      description: |-
        Creates a refund for a specific payment. The refunded amount is credited to your customer usually either via a bank
        transfer or by refunding the amount to your customer's credit card.
    get:
      summary: List payment refunds
      tags:
        - Refunds API
      operationId: list-refunds
      security:
        - apiKey: []
        - oAuth:
            - refunds.read
      description: |-
        Retrieve a list of all refunds created for a specific payment.

        The results are paginated.
  /payments/{paymentId}/refunds/{refundId}:
    get:
      summary: Get payment refund
      tags:
        - Refunds API
      operationId: get-refund
      security:
        - apiKey: []
        - oAuth:
            - refunds.read
      description: Retrieve a single payment refund by its ID and the ID of its parent payment.
    delete:
      summary: Cancel payment refund
      tags:
        - Refunds API
      operationId: cancel-refund
      security:
        - apiKey: []
        - oAuth:
            - refunds.write
      description: |-
        Refunds will be executed with a delay of two hours. Until that time, refunds may be canceled manually via the
        Mollie Dashboard, or by using this endpoint.

        A refund can only be canceled while its `status` field is either `queued` or `pending`. See the
        [Get refund endpoint](get-refund) for more information.
  /refunds:
    get:
      summary: List all refunds
      tags:
        - Refunds API
      operationId: list-all-refunds
      security:
        - apiKey: []
        - oAuth:
            - refunds.read
      description: |-
        Retrieve a list of all of your refunds.

        The results are paginated.
  /payments/{paymentId}/chargebacks:
    get:
      summary: List payment chargebacks
      tags:
        - Chargebacks API
      operationId: list-chargebacks
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: |-
        Retrieve the chargebacks initiated for a specific payment.

        The results are paginated.
  /payments/{paymentId}/chargebacks/{chargebackId}:
    get:
      summary: Get payment chargeback
      tags:
        - Chargebacks API
      operationId: get-chargeback
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: Retrieve a single payment chargeback by its ID and the ID of its parent payment.
  /chargebacks:
    get:
      summary: List all chargebacks
      tags:
        - Chargebacks API
      operationId: list-all-chargebacks
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: |-
        Retrieve all chargebacks initiated for all your payments.

        The results are paginated.
  /payments/{paymentId}/captures:
    post:
      summary: Create capture
      tags:
        - Captures API
      operationId: create-capture
      security:
        - apiKey: []
        - oAuth:
            - payments.write
      description: |-
        Capture an *authorized* payment.

        Some payment methods allow you to first collect a customer's authorization,
        and capture the amount at a later point.

        By default, Mollie captures payments automatically. If however you
        configured your payment with `captureMode: manual`, you can capture the payment using this endpoint after
        having collected the customer's authorization.
    get:
      summary: List captures
      tags:
        - Captures API
      operationId: list-captures
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: |-
        Retrieve a list of all captures created for a specific payment.

        The results are paginated.
  /payments/{paymentId}/captures/{captureId}:
    get:
      summary: Get capture
      tags:
        - Captures API
      operationId: get-capture
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: |-
        Retrieve a single payment capture by its ID and the ID of its parent
        payment.
  /wallets/applepay/sessions:
    post:
      summary: Request Apple Pay payment session
      tags:
        - Wallets API
      operationId: request-apple-pay-payment-session
      security:
        - apiKey: []
        - oAuth:
            - payments.write
      description: |-
        When integrating Apple Pay in your own checkout on the web, you need to
        [provide merchant validation](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/providing_merchant_validation).
        This is normally done using Apple's
        [Requesting an Apple Pay Session](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/requesting_an_apple_pay_payment_session).
        The merchant validation proves to Apple that a validated merchant is calling the Apple Pay Javascript APIs.

        To integrate Apple Pay via Mollie, you will have to call the Mollie API instead of Apple's API. The response of this
        API call can then be passed as-is to the completion method, `completeMerchantValidation`.

        Before requesting an Apple Pay Payment Session, you must place the domain validation file on your server at:
        `https://[domain]/.well-known/apple-developer-merchantid-domain-association`. Without this file, it will not be
        possible to use Apple Pay on your domain.

        Each new transaction requires a new payment session object. Merchant session objects are not reusable, and they
        expire after five minutes.

        Payment sessions cannot be requested directly from the browser. The request must be sent from your server. For the
        full documentation, see the official
        [Apple Pay JS API](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api) documentation.
  /payment-links:
    post:
      summary: Create payment link
      tags:
        - Payment Links API
      operationId: create-payment-link
      security:
        - apiKey: []
        - oAuth:
            - payment-links.write
      description: |-
        With the Payment links API you can generate payment links that by default, unlike regular payments, do not expire.
        The payment link can be shared with your customers and will redirect them to them the payment page where they can
        complete the payment. A [payment](get-payment) will only be created once the customer initiates the payment.
    get:
      summary: List payment links
      tags:
        - Payment Links API
      operationId: list-payment-links
      security:
        - apiKey: []
        - oAuth:
            - payment-links.read
      description: |-
        Retrieve a list of all payment links.

        The results are paginated.
  /payment-links/{paymentLinkId}:
    get:
      summary: Get payment link
      tags:
        - Payment Links API
      operationId: get-payment-link
      security:
        - apiKey: []
        - oAuth:
            - payment-links.read
      description: Retrieve a single payment link by its ID.
    patch:
      summary: Update payment link
      tags:
        - Payment Links API
      operationId: update-payment-link
      security:
        - apiKey: []
        - oAuth:
            - payment-links.write
      description: Certain details of an existing payment link can be updated.
    delete:
      summary: Delete payment link
      tags:
        - Payment Links API
      operationId: delete-payment-link
      security:
        - apiKey: []
        - oAuth:
            - payment-links.write
      description: |-
        Payment links which have not been opened and no payments have been made yet can be deleted entirely.
        This can be useful for removing payment links that have been incorrectly configured or that are no longer relevant.

        Once deleted, the payment link will no longer show up in the API or Mollie dashboard.

        To simply disable a payment link without fully deleting it, you can use the `archived` parameter on the
        [Update payment link](update-payment-link) endpoint instead.
  /payment-links/{paymentLinkId}/payments:
    get:
      summary: Get payment link payments
      tags:
        - Payment Links API
      operationId: get-payment-link-payments
      security:
        - apiKey: []
        - oAuth:
            - payment-links.read
      description: |-
        Retrieve the list of payments for a specific payment link.

        The results are paginated.
  /terminals:
    get:
      summary: List terminals
      tags:
        - Terminals API
      operationId: list-terminals
      security:
        - apiKey: []
        - oAuth:
            - terminals.read
      description: |-
        Retrieve a list of all physical point-of-sale devices.

        The results are paginated.
  /terminals/{terminalId}:
    get:
      summary: Get terminal
      tags:
        - Terminals API
      operationId: get-terminal
      security:
        - apiKey: []
        - oAuth:
            - terminals.read
      description: Retrieve a single terminal by its ID.
  /payments/{paymentId}/routes:
    post:
      operationId: payment-create-route
      summary: Create a delayed route
      tags:
        - Delayed Routing API
      security:
        - apiKey: []
        - oAuth:
            - payments.write
      description: |-
        Create a route for a specific payment.
        The routed amount is credited to the account of your customer.
    get:
      operationId: payment-list-routes
      summary: List payment routes
      tags:
        - Delayed Routing API
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: Retrieve a list of all routes created for a specific payment.
  /customers:
    post:
      summary: Create customer
      tags:
        - Customers API
      operationId: create-customer
      security:
        - apiKey: []
        - oAuth:
            - customers.write
      description: |-
        Creates a simple minimal representation of a customer. Payments, recurring mandates, and subscriptions can be linked
        to this customer object, which simplifies management of recurring payments.

        Once registered, customers will also appear in your Mollie dashboard.
    get:
      summary: List customers
      tags:
        - Customers API
      operationId: list-customers
      security:
        - apiKey: []
        - oAuth:
            - customers.read
      description: |-
        Retrieve a list of all customers.

        The results are paginated.
  /customers/{customerId}:
    get:
      summary: Get customer
      tags:
        - Customers API
      operationId: get-customer
      security:
        - apiKey: []
      description: Retrieve a single customer by its ID.
    patch:
      summary: Update customer
      tags:
        - Customers API
      operationId: update-customer
      security:
        - apiKey: []
      description: |-
        Update an existing customer.

        For an in-depth explanation of each parameter, refer to the [Create customer](create-customer) endpoint.
    delete:
      summary: Delete customer
      tags:
        - Customers API
      operationId: delete-customer
      security:
        - apiKey: []
      description: Delete a customer. All mandates and subscriptions created for this customer will be canceled as well.
  /customers/{customerId}/payments:
    post:
      summary: Create customer payment
      tags:
        - Customers API
      operationId: create-customer-payment
      security:
        - apiKey: []
        - oAuth:
            - payments.write
      description: |-
        Creates a payment for the customer.

        Linking customers to payments enables you to:

        * Keep track of payment preferences for your customers
        * Allow your customers to charge a previously used credit card with a single click in our hosted checkout
        * Improve payment insights in the Mollie dashboard
        * Use recurring payments

        This endpoint is effectively an alias of the [Create payment endpoint](create-payment) with the `customerId`
        parameter predefined.
    get:
      summary: List customer payments
      tags:
        - Customers API
      operationId: list-customer-payments
      security:
        - apiKey: []
        - oAuth:
            - payments.read
      description: Retrieve all payments linked to the customer.
  /customers/{customerId}/mandates:
    post:
      summary: Create mandate
      tags:
        - Mandates API
      operationId: create-mandate
      security:
        - apiKey: []
        - oAuth:
            - mandates.write
      description: |-
        Create a mandate for a specific customer. Mandates allow you to charge a customer's card, PayPal account or bank
        account recurrently.

        It is only possible to create mandates for IBANs and PayPal billing agreements with this endpoint. To create
        mandates for cards, your customers need to perform a 'first payment' with their card.
    get:
      summary: List mandates
      tags:
        - Mandates API
      operationId: list-mandates
      security:
        - apiKey: []
        - oAuth:
            - mandates.read
      description: |-
        Retrieve a list of all mandates.

        The results are paginated.
  /customers/{customerId}/mandates/{mandateId}:
    get:
      summary: Get mandate
      tags:
        - Mandates API
      operationId: get-mandate
      security:
        - apiKey: []
        - oAuth:
            - mandates.read
      description: |-
        Retrieve a single mandate by its ID. Depending on the type of mandate, the object will contain the customer's bank
        account details, card details, or PayPal account details.
    delete:
      summary: Revoke mandate
      tags:
        - Mandates API
      operationId: revoke-mandate
      security:
        - apiKey: []
        - oAuth:
            - mandates.write
      description: |-
        Revoke a customer's mandate. You will no longer be able to charge the customer's bank account or card with this
        mandate, and all connected subscriptions will be canceled.
  /customers/{customerId}/subscriptions:
    post:
      summary: Create subscription
      tags:
        - Subscriptions API
      operationId: create-subscription
      security:
        - apiKey: []
        - oAuth:
            - subscriptions.write
      description: |-
        With subscriptions, you can schedule recurring payments to take place at regular intervals.

        For example, by simply specifying an `amount` and an `interval`, you can create an endless subscription to charge a
        monthly fee, until you cancel the subscription.

        Or, you could use the times parameter to only charge a limited number of times, for example to split a big
        transaction in multiple parts.

        A few example usages:

        `amount[currency]="EUR"` `amount[value]="5.00"` `interval="2 weeks"`
        Your customer will be charged €5 once every two weeks.

        `amount[currency]="EUR"` `amount[value]="20.00"` `interval="1 day" times=5`
        Your customer will be charged €20 every day, for five consecutive days.

        `amount[currency]="EUR"` `amount[value]="10.00"` `interval="1 month"`
        `startDate="2018-04-30"`
        Your customer will be charged €10 on the last day of each month, starting in April 2018.
    get:
      summary: List customer subscriptions
      tags:
        - Subscriptions API
      operationId: list-subscriptions
      security:
        - apiKey: []
        - oAuth:
            - subscriptions.read
      description: |-
        Retrieve all subscriptions of a customer.

        The results are paginated.
  /customers/{customerId}/subscriptions/{subscriptionId}:
    get:
      summary: Get subscription
      tags:
        - Subscriptions API
      operationId: get-subscription
      security:
        - apiKey: []
        - oAuth:
            - subscriptions.read
      description: Retrieve a single subscription by its ID and the ID of its parent customer.
    patch:
      summary: Update subscription
      tags:
        - Subscriptions API
      operationId: update-subscription
      security:
        - apiKey: []
        - oAuth:
            - subscriptions.write
      description: |-
        Update an existing subscription.

        Canceled subscriptions cannot be updated.

        For an in-depth explanation of each parameter, refer to the [Create subscription](create-subscription) endpoint.
    delete:
      summary: Cancel subscription
      tags:
        - Subscriptions API
      operationId: cancel-subscription
      security:
        - apiKey: []
        - oAuth:
            - subscriptions.write
      description: Cancel an existing subscription. Canceling a subscription has no effect on the mandates of the customer.
  /subscriptions:
    get:
      summary: List all subscriptions
      tags:
        - Subscriptions API
      operationId: list-all-subscriptions
      security:
        - apiKey: []
        - oAuth:
            - subscriptions.read
      description: |-
        Retrieve all subscriptions initiated across all your customers.

        The results are paginated.
  /customers/{customerId}/subscriptions/{subscriptionId}/payments:
    get:
      summary: List subscription payments
      tags:
        - Subscriptions API
      operationId: list-subscription-payments
      security:
        - apiKey: []
        - oAuth:
            - subscriptions.read
            - payments.read
      description: |-
        Retrieve all payments of a specific subscription.

        The results are paginated.
  /sales-invoices:
    post:
      summary: Create sales invoice
      tags:
        - Sales Invoices API
      operationId: create-sales-invoice
      security:
        - apiKey: []
        - oAuth:
            - sales-invoices.write
      description: |-
        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        With the Sales Invoice API you can generate sales invoices to send to your customers.
    get:
      summary: List sales invoices
      tags:
        - Sales Invoices API
      operationId: list-sales-invoices
      security:
        - apiKey: []
        - oAuth:
            - sales-invoices.read
      description: |-
        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Retrieve a list of all sales invoices created through the API.

        The results are paginated.
  /sales-invoices/{id}:
    get:
      summary: Get sales invoice
      tags:
        - Sales Invoices API
      operationId: get-sales-invoice
      security:
        - apiKey: []
        - oAuth:
            - sales-invoice.read
      description: |-
        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Retrieve a single sales invoice by its ID.
    patch:
      summary: Update sales invoice
      tags:
        - Sales Invoices API
      operationId: update-sales-invoice
      security:
        - apiKey: []
        - oAuth:
            - sales-invoices.write
      description: |-
        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Certain details of an existing sales invoice can be updated. For `draft` it is all values listed below, but for
        statuses `paid` and `issued` there are certain additional requirements (`paymentDetails` and `emailDetails`,
        respectively).
    delete:
      summary: Delete sales invoice
      tags:
        - Sales Invoices API
      operationId: delete-sales-invoice
      security:
        - apiKey: []
        - oAuth:
            - sales-invoices.write
      description: |-
        > 🚧 Beta feature
        >
        > This feature is currently in beta testing, and the final specification may still change.

        Sales invoices which are in status `draft` can be deleted. For all other statuses, please use the
        [Update sales invoice](update-sales-invoice) endpoint instead.
components:
  securitySchemes:
    apiKey:
      type: http
      scheme: bearer
      x-default: live_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM
    oAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://my.mollie.com/oauth2/authorize
          tokenUrl: https://api.mollie.com/oauth2/tokens
          scopes: {}