/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetClientRequest = {
  /**
   * Provide the ID of the related organization.
   */
  organizationId: string;
  /**
   * This endpoint allows embedding related API items by appending the following values via the `embed` query string
   *
   * @remarks
   * parameter.
   *
   * * `organization`: Include the organization of the client. Available for `signuplink` partners, or for `oauth`
   *   partners with the `organizations.read` scope.
   * * `onboarding`: Include the onboarding status of the client. Available for `signuplink` partners, or for `oauth`
   *   partners with the `onboarding.read` scope.
   * * `capabilities`: Include the [capabilities](list-capabilities) of the client organization.
   *   Available for *oauth* partners with the `onboarding.read` scope.
   */
  embed?: string | null | undefined;
  /**
   * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
   */
  idempotencyKey?: string | undefined;
};

/**
 * The commission object.
 */
export type GetClientCommission = {
  /**
   * The commission count.
   */
  count?: number | undefined;
};

/**
 * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
 */
export type GetClientLinks = {
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  self: models.Url;
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  organization?: models.Url | undefined;
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  onboarding?: models.Url | undefined;
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  documentation?: models.Url | undefined;
};

export type GetClientEmbedded = {
  organization?: models.EntityOrganization | undefined;
  onboarding?: models.EntityOnboardingStatus | undefined;
  capabilities?: models.EntityCapability | undefined;
};

/**
 * The client object.
 */
export type GetClientResponse = {
  /**
   * Indicates the response contains a client object. Will always contain the string `client` for this resource type.
   */
  resource: string;
  /**
   * The identifier uniquely referring to this client. Example: `org_12345678`.
   */
  id: string;
  /**
   * The commission object.
   */
  commission?: GetClientCommission | null | undefined;
  /**
   * The date and time the client organization was created, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
   *
   * @remarks
   * format.
   */
  organizationCreatedAt?: string | undefined;
  /**
   * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
   */
  links: GetClientLinks;
  embedded?: GetClientEmbedded | undefined;
};

/** @internal */
export const GetClientRequest$inboundSchema: z.ZodType<
  GetClientRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  organizationId: z.string(),
  embed: z.nullable(z.string()).optional(),
  "idempotency-key": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "idempotency-key": "idempotencyKey",
  });
});
/** @internal */
export type GetClientRequest$Outbound = {
  organizationId: string;
  embed?: string | null | undefined;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const GetClientRequest$outboundSchema: z.ZodType<
  GetClientRequest$Outbound,
  z.ZodTypeDef,
  GetClientRequest
> = z.object({
  organizationId: z.string(),
  embed: z.nullable(z.string()).optional(),
  idempotencyKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
  });
});

export function getClientRequestToJSON(
  getClientRequest: GetClientRequest,
): string {
  return JSON.stringify(
    GetClientRequest$outboundSchema.parse(getClientRequest),
  );
}
export function getClientRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetClientRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClientRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClientRequest' from JSON`,
  );
}

/** @internal */
export const GetClientCommission$inboundSchema: z.ZodType<
  GetClientCommission,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int().optional(),
});
/** @internal */
export type GetClientCommission$Outbound = {
  count?: number | undefined;
};

/** @internal */
export const GetClientCommission$outboundSchema: z.ZodType<
  GetClientCommission$Outbound,
  z.ZodTypeDef,
  GetClientCommission
> = z.object({
  count: z.number().int().optional(),
});

export function getClientCommissionToJSON(
  getClientCommission: GetClientCommission,
): string {
  return JSON.stringify(
    GetClientCommission$outboundSchema.parse(getClientCommission),
  );
}
export function getClientCommissionFromJSON(
  jsonString: string,
): SafeParseResult<GetClientCommission, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClientCommission$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClientCommission' from JSON`,
  );
}

/** @internal */
export const GetClientLinks$inboundSchema: z.ZodType<
  GetClientLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: models.Url$inboundSchema,
  organization: models.Url$inboundSchema.optional(),
  onboarding: models.Url$inboundSchema.optional(),
  documentation: models.Url$inboundSchema.optional(),
});
/** @internal */
export type GetClientLinks$Outbound = {
  self: models.Url$Outbound;
  organization?: models.Url$Outbound | undefined;
  onboarding?: models.Url$Outbound | undefined;
  documentation?: models.Url$Outbound | undefined;
};

/** @internal */
export const GetClientLinks$outboundSchema: z.ZodType<
  GetClientLinks$Outbound,
  z.ZodTypeDef,
  GetClientLinks
> = z.object({
  self: models.Url$outboundSchema,
  organization: models.Url$outboundSchema.optional(),
  onboarding: models.Url$outboundSchema.optional(),
  documentation: models.Url$outboundSchema.optional(),
});

export function getClientLinksToJSON(getClientLinks: GetClientLinks): string {
  return JSON.stringify(GetClientLinks$outboundSchema.parse(getClientLinks));
}
export function getClientLinksFromJSON(
  jsonString: string,
): SafeParseResult<GetClientLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClientLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClientLinks' from JSON`,
  );
}

/** @internal */
export const GetClientEmbedded$inboundSchema: z.ZodType<
  GetClientEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  organization: models.EntityOrganization$inboundSchema.optional(),
  onboarding: models.EntityOnboardingStatus$inboundSchema.optional(),
  capabilities: models.EntityCapability$inboundSchema.optional(),
});
/** @internal */
export type GetClientEmbedded$Outbound = {
  organization?: models.EntityOrganization$Outbound | undefined;
  onboarding?: models.EntityOnboardingStatus$Outbound | undefined;
  capabilities?: models.EntityCapability$Outbound | undefined;
};

/** @internal */
export const GetClientEmbedded$outboundSchema: z.ZodType<
  GetClientEmbedded$Outbound,
  z.ZodTypeDef,
  GetClientEmbedded
> = z.object({
  organization: models.EntityOrganization$outboundSchema.optional(),
  onboarding: models.EntityOnboardingStatus$outboundSchema.optional(),
  capabilities: models.EntityCapability$outboundSchema.optional(),
});

export function getClientEmbeddedToJSON(
  getClientEmbedded: GetClientEmbedded,
): string {
  return JSON.stringify(
    GetClientEmbedded$outboundSchema.parse(getClientEmbedded),
  );
}
export function getClientEmbeddedFromJSON(
  jsonString: string,
): SafeParseResult<GetClientEmbedded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClientEmbedded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClientEmbedded' from JSON`,
  );
}

/** @internal */
export const GetClientResponse$inboundSchema: z.ZodType<
  GetClientResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource: z.string(),
  id: z.string(),
  commission: z.nullable(z.lazy(() => GetClientCommission$inboundSchema))
    .optional(),
  organizationCreatedAt: z.string().optional(),
  _links: z.lazy(() => GetClientLinks$inboundSchema),
  _embedded: z.lazy(() => GetClientEmbedded$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
    "_embedded": "embedded",
  });
});
/** @internal */
export type GetClientResponse$Outbound = {
  resource: string;
  id: string;
  commission?: GetClientCommission$Outbound | null | undefined;
  organizationCreatedAt?: string | undefined;
  _links: GetClientLinks$Outbound;
  _embedded?: GetClientEmbedded$Outbound | undefined;
};

/** @internal */
export const GetClientResponse$outboundSchema: z.ZodType<
  GetClientResponse$Outbound,
  z.ZodTypeDef,
  GetClientResponse
> = z.object({
  resource: z.string(),
  id: z.string(),
  commission: z.nullable(z.lazy(() => GetClientCommission$outboundSchema))
    .optional(),
  organizationCreatedAt: z.string().optional(),
  links: z.lazy(() => GetClientLinks$outboundSchema),
  embedded: z.lazy(() => GetClientEmbedded$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
    embedded: "_embedded",
  });
});

export function getClientResponseToJSON(
  getClientResponse: GetClientResponse,
): string {
  return JSON.stringify(
    GetClientResponse$outboundSchema.parse(getClientResponse),
  );
}
export function getClientResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetClientResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetClientResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetClientResponse' from JSON`,
  );
}
