/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetProfileGlobals = {
  /**
   * Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
   *
   * @remarks
   * parameter can be omitted. For organization-level credentials such as OAuth access tokens, you can enable test mode by
   * setting the `testmode` query parameter to `true`.
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | undefined;
};

export type GetProfileRequest = {
  /**
   * Provide the ID of the related profile.
   */
  profileId: string;
  /**
   * You can enable test mode by setting the `testmode` query parameter to `true`.
   *
   * @remarks
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | undefined;
  /**
   * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
   */
  idempotencyKey?: string | undefined;
};

/** @internal */
export const GetProfileGlobals$inboundSchema: z.ZodType<
  GetProfileGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  testmode: z.boolean().optional(),
});
/** @internal */
export type GetProfileGlobals$Outbound = {
  testmode?: boolean | undefined;
};

/** @internal */
export const GetProfileGlobals$outboundSchema: z.ZodType<
  GetProfileGlobals$Outbound,
  z.ZodTypeDef,
  GetProfileGlobals
> = z.object({
  testmode: z.boolean().optional(),
});

export function getProfileGlobalsToJSON(
  getProfileGlobals: GetProfileGlobals,
): string {
  return JSON.stringify(
    GetProfileGlobals$outboundSchema.parse(getProfileGlobals),
  );
}
export function getProfileGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetProfileGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProfileGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProfileGlobals' from JSON`,
  );
}

/** @internal */
export const GetProfileRequest$inboundSchema: z.ZodType<
  GetProfileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  profileId: z.string(),
  testmode: z.boolean().optional(),
  "idempotency-key": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "idempotency-key": "idempotencyKey",
  });
});
/** @internal */
export type GetProfileRequest$Outbound = {
  profileId: string;
  testmode?: boolean | undefined;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const GetProfileRequest$outboundSchema: z.ZodType<
  GetProfileRequest$Outbound,
  z.ZodTypeDef,
  GetProfileRequest
> = z.object({
  profileId: z.string(),
  testmode: z.boolean().optional(),
  idempotencyKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
  });
});

export function getProfileRequestToJSON(
  getProfileRequest: GetProfileRequest,
): string {
  return JSON.stringify(
    GetProfileRequest$outboundSchema.parse(getProfileRequest),
  );
}
export function getProfileRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetProfileRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProfileRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProfileRequest' from JSON`,
  );
}
