/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 224546f3f420
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSalesInvoiceGlobals = {
  /**
   * Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
   *
   * @remarks
   * parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
   * setting the `testmode` query parameter to `true`.
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | undefined;
};

export type GetSalesInvoiceRequest = {
  /**
   * Provide the ID of the related sales invoice.
   */
  salesInvoiceId: string;
  /**
   * Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
   *
   * @remarks
   * parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
   * setting the `testmode` query parameter to `true`.
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | undefined;
  /**
   * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
   */
  idempotencyKey?: string | undefined;
};

/** @internal */
export type GetSalesInvoiceRequest$Outbound = {
  salesInvoiceId: string;
  testmode?: boolean | undefined;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const GetSalesInvoiceRequest$outboundSchema: z.ZodType<
  GetSalesInvoiceRequest$Outbound,
  z.ZodTypeDef,
  GetSalesInvoiceRequest
> = z.object({
  salesInvoiceId: z.string(),
  testmode: z.boolean().optional(),
  idempotencyKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
  });
});

export function getSalesInvoiceRequestToJSON(
  getSalesInvoiceRequest: GetSalesInvoiceRequest,
): string {
  return JSON.stringify(
    GetSalesInvoiceRequest$outboundSchema.parse(getSalesInvoiceRequest),
  );
}
