/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 544c6d7e8058
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetUnmatchedCreditTransferRequest = {
  /**
   * Provide the ID of the related unmatched credit transfer.
   */
  unmatchedCreditTransferId: string;
  /**
   * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
   */
  idempotencyKey?: string | undefined;
};

/** @internal */
export type GetUnmatchedCreditTransferRequest$Outbound = {
  unmatchedCreditTransferId: string;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const GetUnmatchedCreditTransferRequest$outboundSchema: z.ZodType<
  GetUnmatchedCreditTransferRequest$Outbound,
  z.ZodTypeDef,
  GetUnmatchedCreditTransferRequest
> = z.object({
  unmatchedCreditTransferId: z.string(),
  idempotencyKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
  });
});

export function getUnmatchedCreditTransferRequestToJSON(
  getUnmatchedCreditTransferRequest: GetUnmatchedCreditTransferRequest,
): string {
  return JSON.stringify(
    GetUnmatchedCreditTransferRequest$outboundSchema.parse(
      getUnmatchedCreditTransferRequest,
    ),
  );
}
