/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1aefa7b044e4
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListAllChargebacksGlobals = {
  /**
   * The identifier referring to the [profile](get-profile) you wish to
   *
   * @remarks
   * retrieve the resources for.
   *
   * Most API credentials are linked to a single profile. In these cases the `profileId` must not be sent. For
   * organization-level credentials such as OAuth access tokens however, the `profileId` parameter is required.
   */
  profileId?: string | undefined;
  /**
   * Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
   *
   * @remarks
   * parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
   * setting the `testmode` query parameter to `true`.
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | undefined;
};

export type ListAllChargebacksRequest = {
  /**
   * Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the
   *
   * @remarks
   * result set.
   */
  from?: string | undefined;
  /**
   * The maximum number of items to return. Defaults to 50 items.
   */
  limit?: number | null | undefined;
  /**
   * This endpoint allows you to embed additional information via the
   *
   * @remarks
   * `embed` query string parameter.
   */
  embed?: string | null | undefined;
  /**
   * Used for setting the direction of the result set. Defaults to descending order, meaning the results are ordered from
   *
   * @remarks
   * newest to oldest.
   */
  sort?: models.Sorting | undefined;
  /**
   * The identifier referring to the [profile](get-profile) you wish to
   *
   * @remarks
   * retrieve chargebacks for.
   *
   * Most API credentials are linked to a single profile. In these cases the
   * `profileId` is already implied.
   *
   * To retrieve all chargebacks across the organization, use an
   * organization-level API credential and omit the `profileId` parameter.
   */
  profileId?: string | undefined;
  /**
   * Most API credentials are specifically created for either live mode or test mode. In those cases the `testmode` query
   *
   * @remarks
   * parameter must not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by
   * setting the `testmode` query parameter to `true`.
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | undefined;
  /**
   * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
   */
  idempotencyKey?: string | undefined;
};

export type ListAllChargebacksEmbedded = {
  /**
   * A list of chargeback objects.
   */
  chargebacks: Array<models.ListEntityChargeback>;
};

/**
 * A list of chargeback objects.
 */
export type ListAllChargebacksResponseBody = {
  /**
   * The number of items in this result set. If more items are available, a `_links.next` URL will be present in the result
   *
   * @remarks
   * as well.
   *
   * The maximum number of items per result set is controlled by the `limit` property provided in the request. The default
   * limit is 50 items.
   */
  count: number;
  embedded: ListAllChargebacksEmbedded;
  /**
   * Links to help navigate through the lists of items. Every URL object will contain an `href` and a `type` field.
   */
  links: models.ListLinks;
};

export type ListAllChargebacksResponse = {
  result: ListAllChargebacksResponseBody;
};

/** @internal */
export type ListAllChargebacksRequest$Outbound = {
  from?: string | undefined;
  limit?: number | null | undefined;
  embed?: string | null | undefined;
  sort?: string | undefined;
  profileId?: string | undefined;
  testmode?: boolean | undefined;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const ListAllChargebacksRequest$outboundSchema: z.ZodType<
  ListAllChargebacksRequest$Outbound,
  z.ZodTypeDef,
  ListAllChargebacksRequest
> = z.object({
  from: z.string().optional(),
  limit: z.nullable(z.number().int()).optional(),
  embed: z.nullable(z.string()).optional(),
  sort: models.Sorting$outboundSchema.optional(),
  profileId: z.string().optional(),
  testmode: z.boolean().optional(),
  idempotencyKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
  });
});

export function listAllChargebacksRequestToJSON(
  listAllChargebacksRequest: ListAllChargebacksRequest,
): string {
  return JSON.stringify(
    ListAllChargebacksRequest$outboundSchema.parse(listAllChargebacksRequest),
  );
}

/** @internal */
export const ListAllChargebacksEmbedded$inboundSchema: z.ZodType<
  ListAllChargebacksEmbedded,
  z.ZodTypeDef,
  unknown
> = z.object({
  chargebacks: z.array(models.ListEntityChargeback$inboundSchema),
});

export function listAllChargebacksEmbeddedFromJSON(
  jsonString: string,
): SafeParseResult<ListAllChargebacksEmbedded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAllChargebacksEmbedded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllChargebacksEmbedded' from JSON`,
  );
}

/** @internal */
export const ListAllChargebacksResponseBody$inboundSchema: z.ZodType<
  ListAllChargebacksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  count: z.number().int(),
  _embedded: z.lazy(() => ListAllChargebacksEmbedded$inboundSchema),
  _links: models.ListLinks$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "_embedded": "embedded",
    "_links": "links",
  });
});

export function listAllChargebacksResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListAllChargebacksResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAllChargebacksResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllChargebacksResponseBody' from JSON`,
  );
}

/** @internal */
export const ListAllChargebacksResponse$inboundSchema: z.ZodType<
  ListAllChargebacksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => ListAllChargebacksResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listAllChargebacksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAllChargebacksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAllChargebacksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllChargebacksResponse' from JSON`,
  );
}
