/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b187f21ad9b8
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ReleaseAuthorizationRequestBody = {
  /**
   * The identifier referring to the [profile](get-profile) this entity belongs to.
   *
   * @remarks
   *
   * Most API credentials are linked to a single profile. In these cases the `profileId` can be omitted in the creation
   * request. For organization-level credentials such as OAuth access tokens however, the `profileId` parameter is
   * required.
   */
  profileId?: string | undefined;
  /**
   * Whether to create the entity in test mode or live mode.
   *
   * @remarks
   *
   * Most API credentials are specifically created for either live mode or test mode, in which case this parameter must
   * not be sent. For organization-level credentials such as OAuth access tokens, you can enable test mode by setting
   * `testmode` to `true`.
   */
  testmode?: boolean | null | undefined;
};

export type ReleaseAuthorizationRequest = {
  /**
   * Provide the ID of the related payment.
   */
  paymentId: string;
  /**
   * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
   */
  idempotencyKey?: string | undefined;
  requestBody?: ReleaseAuthorizationRequestBody | undefined;
};

/** @internal */
export type ReleaseAuthorizationRequestBody$Outbound = {
  profileId?: string | undefined;
  testmode?: boolean | null | undefined;
};

/** @internal */
export const ReleaseAuthorizationRequestBody$outboundSchema: z.ZodType<
  ReleaseAuthorizationRequestBody$Outbound,
  z.ZodTypeDef,
  ReleaseAuthorizationRequestBody
> = z.object({
  profileId: z.string().optional(),
  testmode: z.nullable(z.boolean()).optional(),
});

export function releaseAuthorizationRequestBodyToJSON(
  releaseAuthorizationRequestBody: ReleaseAuthorizationRequestBody,
): string {
  return JSON.stringify(
    ReleaseAuthorizationRequestBody$outboundSchema.parse(
      releaseAuthorizationRequestBody,
    ),
  );
}

/** @internal */
export type ReleaseAuthorizationRequest$Outbound = {
  paymentId: string;
  "idempotency-key"?: string | undefined;
  RequestBody?: ReleaseAuthorizationRequestBody$Outbound | undefined;
};

/** @internal */
export const ReleaseAuthorizationRequest$outboundSchema: z.ZodType<
  ReleaseAuthorizationRequest$Outbound,
  z.ZodTypeDef,
  ReleaseAuthorizationRequest
> = z.object({
  paymentId: z.string(),
  idempotencyKey: z.string().optional(),
  requestBody: z.lazy(() => ReleaseAuthorizationRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
    requestBody: "RequestBody",
  });
});

export function releaseAuthorizationRequestToJSON(
  releaseAuthorizationRequest: ReleaseAuthorizationRequest,
): string {
  return JSON.stringify(
    ReleaseAuthorizationRequest$outboundSchema.parse(
      releaseAuthorizationRequest,
    ),
  );
}
