/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The list of events to enable for this webhook. You may specify `'*'` to add all events, except those
 *
 * @remarks
 * that require explicit selection. Separate multiple event types with a comma.
 */
export const UpdateWebhookWebhookEventTypesRequest = {
  PaymentLinkPaid: "payment-link.paid",
  BalanceTransactionCreated: "balance-transaction.created",
  SalesInvoiceCreated: "sales-invoice.created",
  SalesInvoiceIssued: "sales-invoice.issued",
  SalesInvoiceCanceled: "sales-invoice.canceled",
  SalesInvoicePaid: "sales-invoice.paid",
  Wildcard: "*",
} as const;
/**
 * The list of events to enable for this webhook. You may specify `'*'` to add all events, except those
 *
 * @remarks
 * that require explicit selection. Separate multiple event types with a comma.
 */
export type UpdateWebhookWebhookEventTypesRequest = ClosedEnum<
  typeof UpdateWebhookWebhookEventTypesRequest
>;

export type UpdateWebhookRequestBody = {
  /**
   * A name that identifies the webhook.
   */
  name?: string | undefined;
  /**
   * The URL Mollie will send the events to. This URL must be publicly accessible.
   */
  url?: string | undefined;
  /**
   * The list of events to enable for this webhook. You may specify `'*'` to add all events, except those
   *
   * @remarks
   * that require explicit selection. Separate multiple event types with a comma.
   */
  webhookEventTypes?: UpdateWebhookWebhookEventTypesRequest | undefined;
  /**
   * Most API credentials are specifically created for either live mode or test mode. For organization-level credentials
   *
   * @remarks
   * such as OAuth access tokens, you can enable test mode by setting `testmode` to `true`.
   *
   * Test entities cannot be retrieved when the endpoint is set to live mode, and vice versa.
   */
  testmode?: boolean | null | undefined;
};

export type UpdateWebhookRequest = {
  /**
   * Provide the ID of the item you want to perform this operation on.
   */
  id: string;
  requestBody?: UpdateWebhookRequestBody | undefined;
};

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type UpdateWebhookUnprocessableEntityDocumentation = {
  href: string;
  type: string;
};

export type UpdateWebhookUnprocessableEntityLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation: UpdateWebhookUnprocessableEntityDocumentation;
};

/**
 * The URL to the generic Mollie API error handling guide.
 */
export type UpdateWebhookNotFoundDocumentation = {
  href: string;
  type: string;
};

export type UpdateWebhookNotFoundLinks = {
  /**
   * The URL to the generic Mollie API error handling guide.
   */
  documentation: UpdateWebhookNotFoundDocumentation;
};

/**
 * The event's type
 */
export const UpdateWebhookEventTypeWebhookEventTypes = {
  PaymentLinkPaid: "payment-link.paid",
  BalanceTransactionCreated: "balance-transaction.created",
  SalesInvoiceCreated: "sales-invoice.created",
  SalesInvoiceIssued: "sales-invoice.issued",
  SalesInvoiceCanceled: "sales-invoice.canceled",
  SalesInvoicePaid: "sales-invoice.paid",
  Wildcard: "*",
} as const;
/**
 * The event's type
 */
export type UpdateWebhookEventTypeWebhookEventTypes = ClosedEnum<
  typeof UpdateWebhookEventTypeWebhookEventTypes
>;

/**
 * The subscription's current status.
 */
export const UpdateWebhookStatus = {
  Enabled: "enabled",
  Blocked: "blocked",
  Disabled: "disabled",
  Deleted: "deleted",
} as const;
/**
 * The subscription's current status.
 */
export type UpdateWebhookStatus = ClosedEnum<typeof UpdateWebhookStatus>;

/**
 * Whether this entity was created in live mode or in test mode.
 */
export const UpdateWebhookMode = {
  Live: "live",
  Test: "test",
} as const;
/**
 * Whether this entity was created in live mode or in test mode.
 */
export type UpdateWebhookMode = ClosedEnum<typeof UpdateWebhookMode>;

/**
 * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
 */
export type UpdateWebhookDocumentation = {
  /**
   * The actual URL string.
   */
  href: string;
  /**
   * The content type of the page or endpoint the URL points to.
   */
  type: string;
};

/**
 * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
 */
export type UpdateWebhookLinks = {
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  documentation: UpdateWebhookDocumentation;
};

/**
 * The webhook object.
 */
export type UpdateWebhookResponse = {
  /**
   * Indicates the response contains a webhook subscription object.
   *
   * @remarks
   * Will always contain the string `webhook` for this endpoint.
   */
  resource: string;
  /**
   * The identifier uniquely referring to this subscription.
   */
  id: string;
  /**
   * The subscription's events destination.
   */
  url: string;
  /**
   * The identifier uniquely referring to the profile that created the subscription.
   */
  profileId: string | null;
  /**
   * The subscription's date time of creation.
   */
  createdAt: string;
  /**
   * The subscription's name.
   */
  name: string;
  /**
   * The events types that are subscribed.
   */
  eventTypes: Array<UpdateWebhookEventTypeWebhookEventTypes>;
  /**
   * The subscription's current status.
   */
  status: UpdateWebhookStatus;
  /**
   * Whether this entity was created in live mode or in test mode.
   */
  mode: UpdateWebhookMode;
  /**
   * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
   */
  links: UpdateWebhookLinks;
};

/** @internal */
export const UpdateWebhookWebhookEventTypesRequest$inboundSchema:
  z.ZodNativeEnum<typeof UpdateWebhookWebhookEventTypesRequest> = z.nativeEnum(
    UpdateWebhookWebhookEventTypesRequest,
  );

/** @internal */
export const UpdateWebhookWebhookEventTypesRequest$outboundSchema:
  z.ZodNativeEnum<typeof UpdateWebhookWebhookEventTypesRequest> =
    UpdateWebhookWebhookEventTypesRequest$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookWebhookEventTypesRequest$ {
  /** @deprecated use `UpdateWebhookWebhookEventTypesRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateWebhookWebhookEventTypesRequest$inboundSchema;
  /** @deprecated use `UpdateWebhookWebhookEventTypesRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateWebhookWebhookEventTypesRequest$outboundSchema;
}

/** @internal */
export const UpdateWebhookRequestBody$inboundSchema: z.ZodType<
  UpdateWebhookRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  url: z.string().optional(),
  eventTypes: UpdateWebhookWebhookEventTypesRequest$inboundSchema.optional(),
  testmode: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    "eventTypes": "webhookEventTypes",
  });
});

/** @internal */
export type UpdateWebhookRequestBody$Outbound = {
  name?: string | undefined;
  url?: string | undefined;
  eventTypes?: string | undefined;
  testmode?: boolean | null | undefined;
};

/** @internal */
export const UpdateWebhookRequestBody$outboundSchema: z.ZodType<
  UpdateWebhookRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateWebhookRequestBody
> = z.object({
  name: z.string().optional(),
  url: z.string().optional(),
  webhookEventTypes: UpdateWebhookWebhookEventTypesRequest$outboundSchema
    .optional(),
  testmode: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    webhookEventTypes: "eventTypes",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookRequestBody$ {
  /** @deprecated use `UpdateWebhookRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookRequestBody$inboundSchema;
  /** @deprecated use `UpdateWebhookRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookRequestBody$outboundSchema;
  /** @deprecated use `UpdateWebhookRequestBody$Outbound` instead. */
  export type Outbound = UpdateWebhookRequestBody$Outbound;
}

export function updateWebhookRequestBodyToJSON(
  updateWebhookRequestBody: UpdateWebhookRequestBody,
): string {
  return JSON.stringify(
    UpdateWebhookRequestBody$outboundSchema.parse(updateWebhookRequestBody),
  );
}

export function updateWebhookRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookRequest$inboundSchema: z.ZodType<
  UpdateWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => UpdateWebhookRequestBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateWebhookRequest$Outbound = {
  id: string;
  RequestBody?: UpdateWebhookRequestBody$Outbound | undefined;
};

/** @internal */
export const UpdateWebhookRequest$outboundSchema: z.ZodType<
  UpdateWebhookRequest$Outbound,
  z.ZodTypeDef,
  UpdateWebhookRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateWebhookRequestBody$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookRequest$ {
  /** @deprecated use `UpdateWebhookRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookRequest$inboundSchema;
  /** @deprecated use `UpdateWebhookRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookRequest$outboundSchema;
  /** @deprecated use `UpdateWebhookRequest$Outbound` instead. */
  export type Outbound = UpdateWebhookRequest$Outbound;
}

export function updateWebhookRequestToJSON(
  updateWebhookRequest: UpdateWebhookRequest,
): string {
  return JSON.stringify(
    UpdateWebhookRequest$outboundSchema.parse(updateWebhookRequest),
  );
}

export function updateWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookRequest' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookUnprocessableEntityDocumentation$inboundSchema:
  z.ZodType<
    UpdateWebhookUnprocessableEntityDocumentation,
    z.ZodTypeDef,
    unknown
  > = z.object({
    href: z.string(),
    type: z.string(),
  });

/** @internal */
export type UpdateWebhookUnprocessableEntityDocumentation$Outbound = {
  href: string;
  type: string;
};

/** @internal */
export const UpdateWebhookUnprocessableEntityDocumentation$outboundSchema:
  z.ZodType<
    UpdateWebhookUnprocessableEntityDocumentation$Outbound,
    z.ZodTypeDef,
    UpdateWebhookUnprocessableEntityDocumentation
  > = z.object({
    href: z.string(),
    type: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookUnprocessableEntityDocumentation$ {
  /** @deprecated use `UpdateWebhookUnprocessableEntityDocumentation$inboundSchema` instead. */
  export const inboundSchema =
    UpdateWebhookUnprocessableEntityDocumentation$inboundSchema;
  /** @deprecated use `UpdateWebhookUnprocessableEntityDocumentation$outboundSchema` instead. */
  export const outboundSchema =
    UpdateWebhookUnprocessableEntityDocumentation$outboundSchema;
  /** @deprecated use `UpdateWebhookUnprocessableEntityDocumentation$Outbound` instead. */
  export type Outbound = UpdateWebhookUnprocessableEntityDocumentation$Outbound;
}

export function updateWebhookUnprocessableEntityDocumentationToJSON(
  updateWebhookUnprocessableEntityDocumentation:
    UpdateWebhookUnprocessableEntityDocumentation,
): string {
  return JSON.stringify(
    UpdateWebhookUnprocessableEntityDocumentation$outboundSchema.parse(
      updateWebhookUnprocessableEntityDocumentation,
    ),
  );
}

export function updateWebhookUnprocessableEntityDocumentationFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateWebhookUnprocessableEntityDocumentation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateWebhookUnprocessableEntityDocumentation$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateWebhookUnprocessableEntityDocumentation' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookUnprocessableEntityLinks$inboundSchema: z.ZodType<
  UpdateWebhookUnprocessableEntityLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() =>
    UpdateWebhookUnprocessableEntityDocumentation$inboundSchema
  ),
});

/** @internal */
export type UpdateWebhookUnprocessableEntityLinks$Outbound = {
  documentation: UpdateWebhookUnprocessableEntityDocumentation$Outbound;
};

/** @internal */
export const UpdateWebhookUnprocessableEntityLinks$outboundSchema: z.ZodType<
  UpdateWebhookUnprocessableEntityLinks$Outbound,
  z.ZodTypeDef,
  UpdateWebhookUnprocessableEntityLinks
> = z.object({
  documentation: z.lazy(() =>
    UpdateWebhookUnprocessableEntityDocumentation$outboundSchema
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookUnprocessableEntityLinks$ {
  /** @deprecated use `UpdateWebhookUnprocessableEntityLinks$inboundSchema` instead. */
  export const inboundSchema =
    UpdateWebhookUnprocessableEntityLinks$inboundSchema;
  /** @deprecated use `UpdateWebhookUnprocessableEntityLinks$outboundSchema` instead. */
  export const outboundSchema =
    UpdateWebhookUnprocessableEntityLinks$outboundSchema;
  /** @deprecated use `UpdateWebhookUnprocessableEntityLinks$Outbound` instead. */
  export type Outbound = UpdateWebhookUnprocessableEntityLinks$Outbound;
}

export function updateWebhookUnprocessableEntityLinksToJSON(
  updateWebhookUnprocessableEntityLinks: UpdateWebhookUnprocessableEntityLinks,
): string {
  return JSON.stringify(
    UpdateWebhookUnprocessableEntityLinks$outboundSchema.parse(
      updateWebhookUnprocessableEntityLinks,
    ),
  );
}

export function updateWebhookUnprocessableEntityLinksFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookUnprocessableEntityLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateWebhookUnprocessableEntityLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookUnprocessableEntityLinks' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookNotFoundDocumentation$inboundSchema: z.ZodType<
  UpdateWebhookNotFoundDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  type: z.string(),
});

/** @internal */
export type UpdateWebhookNotFoundDocumentation$Outbound = {
  href: string;
  type: string;
};

/** @internal */
export const UpdateWebhookNotFoundDocumentation$outboundSchema: z.ZodType<
  UpdateWebhookNotFoundDocumentation$Outbound,
  z.ZodTypeDef,
  UpdateWebhookNotFoundDocumentation
> = z.object({
  href: z.string(),
  type: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookNotFoundDocumentation$ {
  /** @deprecated use `UpdateWebhookNotFoundDocumentation$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookNotFoundDocumentation$inboundSchema;
  /** @deprecated use `UpdateWebhookNotFoundDocumentation$outboundSchema` instead. */
  export const outboundSchema =
    UpdateWebhookNotFoundDocumentation$outboundSchema;
  /** @deprecated use `UpdateWebhookNotFoundDocumentation$Outbound` instead. */
  export type Outbound = UpdateWebhookNotFoundDocumentation$Outbound;
}

export function updateWebhookNotFoundDocumentationToJSON(
  updateWebhookNotFoundDocumentation: UpdateWebhookNotFoundDocumentation,
): string {
  return JSON.stringify(
    UpdateWebhookNotFoundDocumentation$outboundSchema.parse(
      updateWebhookNotFoundDocumentation,
    ),
  );
}

export function updateWebhookNotFoundDocumentationFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookNotFoundDocumentation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateWebhookNotFoundDocumentation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookNotFoundDocumentation' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookNotFoundLinks$inboundSchema: z.ZodType<
  UpdateWebhookNotFoundLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => UpdateWebhookNotFoundDocumentation$inboundSchema),
});

/** @internal */
export type UpdateWebhookNotFoundLinks$Outbound = {
  documentation: UpdateWebhookNotFoundDocumentation$Outbound;
};

/** @internal */
export const UpdateWebhookNotFoundLinks$outboundSchema: z.ZodType<
  UpdateWebhookNotFoundLinks$Outbound,
  z.ZodTypeDef,
  UpdateWebhookNotFoundLinks
> = z.object({
  documentation: z.lazy(() =>
    UpdateWebhookNotFoundDocumentation$outboundSchema
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookNotFoundLinks$ {
  /** @deprecated use `UpdateWebhookNotFoundLinks$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookNotFoundLinks$inboundSchema;
  /** @deprecated use `UpdateWebhookNotFoundLinks$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookNotFoundLinks$outboundSchema;
  /** @deprecated use `UpdateWebhookNotFoundLinks$Outbound` instead. */
  export type Outbound = UpdateWebhookNotFoundLinks$Outbound;
}

export function updateWebhookNotFoundLinksToJSON(
  updateWebhookNotFoundLinks: UpdateWebhookNotFoundLinks,
): string {
  return JSON.stringify(
    UpdateWebhookNotFoundLinks$outboundSchema.parse(updateWebhookNotFoundLinks),
  );
}

export function updateWebhookNotFoundLinksFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookNotFoundLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookNotFoundLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookNotFoundLinks' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookEventTypeWebhookEventTypes$inboundSchema:
  z.ZodNativeEnum<typeof UpdateWebhookEventTypeWebhookEventTypes> = z
    .nativeEnum(UpdateWebhookEventTypeWebhookEventTypes);

/** @internal */
export const UpdateWebhookEventTypeWebhookEventTypes$outboundSchema:
  z.ZodNativeEnum<typeof UpdateWebhookEventTypeWebhookEventTypes> =
    UpdateWebhookEventTypeWebhookEventTypes$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookEventTypeWebhookEventTypes$ {
  /** @deprecated use `UpdateWebhookEventTypeWebhookEventTypes$inboundSchema` instead. */
  export const inboundSchema =
    UpdateWebhookEventTypeWebhookEventTypes$inboundSchema;
  /** @deprecated use `UpdateWebhookEventTypeWebhookEventTypes$outboundSchema` instead. */
  export const outboundSchema =
    UpdateWebhookEventTypeWebhookEventTypes$outboundSchema;
}

/** @internal */
export const UpdateWebhookStatus$inboundSchema: z.ZodNativeEnum<
  typeof UpdateWebhookStatus
> = z.nativeEnum(UpdateWebhookStatus);

/** @internal */
export const UpdateWebhookStatus$outboundSchema: z.ZodNativeEnum<
  typeof UpdateWebhookStatus
> = UpdateWebhookStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookStatus$ {
  /** @deprecated use `UpdateWebhookStatus$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookStatus$inboundSchema;
  /** @deprecated use `UpdateWebhookStatus$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookStatus$outboundSchema;
}

/** @internal */
export const UpdateWebhookMode$inboundSchema: z.ZodNativeEnum<
  typeof UpdateWebhookMode
> = z.nativeEnum(UpdateWebhookMode);

/** @internal */
export const UpdateWebhookMode$outboundSchema: z.ZodNativeEnum<
  typeof UpdateWebhookMode
> = UpdateWebhookMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookMode$ {
  /** @deprecated use `UpdateWebhookMode$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookMode$inboundSchema;
  /** @deprecated use `UpdateWebhookMode$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookMode$outboundSchema;
}

/** @internal */
export const UpdateWebhookDocumentation$inboundSchema: z.ZodType<
  UpdateWebhookDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string(),
  type: z.string(),
});

/** @internal */
export type UpdateWebhookDocumentation$Outbound = {
  href: string;
  type: string;
};

/** @internal */
export const UpdateWebhookDocumentation$outboundSchema: z.ZodType<
  UpdateWebhookDocumentation$Outbound,
  z.ZodTypeDef,
  UpdateWebhookDocumentation
> = z.object({
  href: z.string(),
  type: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookDocumentation$ {
  /** @deprecated use `UpdateWebhookDocumentation$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookDocumentation$inboundSchema;
  /** @deprecated use `UpdateWebhookDocumentation$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookDocumentation$outboundSchema;
  /** @deprecated use `UpdateWebhookDocumentation$Outbound` instead. */
  export type Outbound = UpdateWebhookDocumentation$Outbound;
}

export function updateWebhookDocumentationToJSON(
  updateWebhookDocumentation: UpdateWebhookDocumentation,
): string {
  return JSON.stringify(
    UpdateWebhookDocumentation$outboundSchema.parse(updateWebhookDocumentation),
  );
}

export function updateWebhookDocumentationFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookDocumentation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookDocumentation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookDocumentation' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookLinks$inboundSchema: z.ZodType<
  UpdateWebhookLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentation: z.lazy(() => UpdateWebhookDocumentation$inboundSchema),
});

/** @internal */
export type UpdateWebhookLinks$Outbound = {
  documentation: UpdateWebhookDocumentation$Outbound;
};

/** @internal */
export const UpdateWebhookLinks$outboundSchema: z.ZodType<
  UpdateWebhookLinks$Outbound,
  z.ZodTypeDef,
  UpdateWebhookLinks
> = z.object({
  documentation: z.lazy(() => UpdateWebhookDocumentation$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookLinks$ {
  /** @deprecated use `UpdateWebhookLinks$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookLinks$inboundSchema;
  /** @deprecated use `UpdateWebhookLinks$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookLinks$outboundSchema;
  /** @deprecated use `UpdateWebhookLinks$Outbound` instead. */
  export type Outbound = UpdateWebhookLinks$Outbound;
}

export function updateWebhookLinksToJSON(
  updateWebhookLinks: UpdateWebhookLinks,
): string {
  return JSON.stringify(
    UpdateWebhookLinks$outboundSchema.parse(updateWebhookLinks),
  );
}

export function updateWebhookLinksFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookLinks' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookResponse$inboundSchema: z.ZodType<
  UpdateWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource: z.string(),
  id: z.string(),
  url: z.string(),
  profileId: z.nullable(z.string()),
  createdAt: z.string(),
  name: z.string(),
  eventTypes: z.array(UpdateWebhookEventTypeWebhookEventTypes$inboundSchema),
  status: UpdateWebhookStatus$inboundSchema,
  mode: UpdateWebhookMode$inboundSchema,
  _links: z.lazy(() => UpdateWebhookLinks$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

/** @internal */
export type UpdateWebhookResponse$Outbound = {
  resource: string;
  id: string;
  url: string;
  profileId: string | null;
  createdAt: string;
  name: string;
  eventTypes: Array<string>;
  status: string;
  mode: string;
  _links: UpdateWebhookLinks$Outbound;
};

/** @internal */
export const UpdateWebhookResponse$outboundSchema: z.ZodType<
  UpdateWebhookResponse$Outbound,
  z.ZodTypeDef,
  UpdateWebhookResponse
> = z.object({
  resource: z.string(),
  id: z.string(),
  url: z.string(),
  profileId: z.nullable(z.string()),
  createdAt: z.string(),
  name: z.string(),
  eventTypes: z.array(UpdateWebhookEventTypeWebhookEventTypes$outboundSchema),
  status: UpdateWebhookStatus$outboundSchema,
  mode: UpdateWebhookMode$outboundSchema,
  links: z.lazy(() => UpdateWebhookLinks$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookResponse$ {
  /** @deprecated use `UpdateWebhookResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookResponse$inboundSchema;
  /** @deprecated use `UpdateWebhookResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookResponse$outboundSchema;
  /** @deprecated use `UpdateWebhookResponse$Outbound` instead. */
  export type Outbound = UpdateWebhookResponse$Outbound;
}

export function updateWebhookResponseToJSON(
  updateWebhookResponse: UpdateWebhookResponse,
): string {
  return JSON.stringify(
    UpdateWebhookResponse$outboundSchema.parse(updateWebhookResponse),
  );
}

export function updateWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookResponse' from JSON`,
  );
}
