/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7d69a98c9024
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VerifyPayeeRequest = {
  /**
   * A unique key to ensure idempotent requests. This key should be a UUID v4 string.
   */
  idempotencyKey?: string | undefined;
  verificationOfPayeeRequest?: models.VerificationOfPayeeRequest | undefined;
};

/** @internal */
export const VerifyPayeeRequest$inboundSchema: z.ZodType<
  VerifyPayeeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "idempotency-key": z.string().optional(),
  "verification-of-payee-request": models
    .VerificationOfPayeeRequest$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "idempotency-key": "idempotencyKey",
    "verification-of-payee-request": "verificationOfPayeeRequest",
  });
});
/** @internal */
export type VerifyPayeeRequest$Outbound = {
  "idempotency-key"?: string | undefined;
  "verification-of-payee-request"?:
    | models.VerificationOfPayeeRequest$Outbound
    | undefined;
};

/** @internal */
export const VerifyPayeeRequest$outboundSchema: z.ZodType<
  VerifyPayeeRequest$Outbound,
  z.ZodTypeDef,
  VerifyPayeeRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  verificationOfPayeeRequest: models.VerificationOfPayeeRequest$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
    verificationOfPayeeRequest: "verification-of-payee-request",
  });
});

export function verifyPayeeRequestToJSON(
  verifyPayeeRequest: VerifyPayeeRequest,
): string {
  return JSON.stringify(
    VerifyPayeeRequest$outboundSchema.parse(verifyPayeeRequest),
  );
}
export function verifyPayeeRequestFromJSON(
  jsonString: string,
): SafeParseResult<VerifyPayeeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerifyPayeeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerifyPayeeRequest' from JSON`,
  );
}
