/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const BalanceCardIssuer = {
  Amex: "amex",
  Maestro: "maestro",
  CarteBancaire: "carte-bancaire",
  Other: "other",
} as const;
export type BalanceCardIssuer = OpenEnum<typeof BalanceCardIssuer>;

/** @internal */
export const BalanceCardIssuer$inboundSchema: z.ZodType<
  BalanceCardIssuer,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(BalanceCardIssuer);
/** @internal */
export const BalanceCardIssuer$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  BalanceCardIssuer
> = openEnums.outboundSchema(BalanceCardIssuer);
