/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 65e8ad895881
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AccountNumberFormatResponse,
  AccountNumberFormatResponse$inboundSchema,
  AccountNumberFormatResponse$outboundSchema,
} from "./accountnumberformatresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The bank account details of the creditor (recipient) for Verification of Payee.
 */
export type CreditorBankAccountResponse = {
  /**
   * The full name of the creditor account holder to verify against bank records.
   */
  accountHolderName: string;
  /**
   * The format of the account number.
   */
  format: AccountNumberFormatResponse;
  /**
   * The bank account details of the creditor.
   */
  accountNumber: string;
};

/** @internal */
export const CreditorBankAccountResponse$inboundSchema: z.ZodType<
  CreditorBankAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountHolderName: z.string(),
  format: AccountNumberFormatResponse$inboundSchema,
  accountNumber: z.string(),
});
/** @internal */
export type CreditorBankAccountResponse$Outbound = {
  accountHolderName: string;
  format: string;
  accountNumber: string;
};

/** @internal */
export const CreditorBankAccountResponse$outboundSchema: z.ZodType<
  CreditorBankAccountResponse$Outbound,
  z.ZodTypeDef,
  CreditorBankAccountResponse
> = z.object({
  accountHolderName: z.string(),
  format: AccountNumberFormatResponse$outboundSchema,
  accountNumber: z.string(),
});

export function creditorBankAccountResponseToJSON(
  creditorBankAccountResponse: CreditorBankAccountResponse,
): string {
  return JSON.stringify(
    CreditorBankAccountResponse$outboundSchema.parse(
      creditorBankAccountResponse,
    ),
  );
}
export function creditorBankAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreditorBankAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditorBankAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditorBankAccountResponse' from JSON`,
  );
}
