/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ace02317ac30
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
import { Amount, Amount$inboundSchema } from "./amount.js";
import {
  DraftTransferParty,
  DraftTransferParty$inboundSchema,
} from "./drafttransferparty.js";
import {
  DraftTransferStatusHistoryEntryResponse,
  DraftTransferStatusHistoryEntryResponse$inboundSchema,
} from "./drafttransferstatushistoryentryresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Mode, Mode$inboundSchema } from "./mode.js";

/**
 * Whether the draft transfer was created via this API, or created in Mollie Apps.
 */
export const DraftTransferResponseSource = {
  Api: "api",
  MollieApp: "mollie-app",
} as const;
/**
 * Whether the draft transfer was created via this API, or created in Mollie Apps.
 */
export type DraftTransferResponseSource = OpenEnum<
  typeof DraftTransferResponseSource
>;

/**
 * The bank account details of the party.
 */
export type DraftTransferResponseAccount = {
  /**
   * The IBAN (International Bank Account Number) of the account holder.
   */
  iban: string;
};

/**
 * The debtor (sender) of the draft transfer, resolved from `debtorIban` at creation time.
 */
export type DraftTransferResponseDebtor = {
  /**
   * The full name of the account holder.
   */
  fullName: string;
  /**
   * The bank account details of the party.
   */
  account: DraftTransferResponseAccount;
};

/**
 * The status of the draft transfer.
 */
export const DraftTransferResponseStatus = {
  AwaitingInitiation: "awaiting-initiation",
  Initiated: "initiated",
  Declined: "declined",
} as const;
/**
 * The status of the draft transfer.
 */
export type DraftTransferResponseStatus = OpenEnum<
  typeof DraftTransferResponseStatus
>;

/**
 * The URL to this draft transfer.
 */
export type DraftTransferResponseSelf = {
  href?: string | undefined;
  type?: string | undefined;
};

/**
 * The URL to the documentation of this endpoint.
 */
export type DraftTransferResponseDocumentation = {
  href?: string | undefined;
  type?: string | undefined;
};

/**
 * Links to related resources.
 */
export type DraftTransferResponseLinks = {
  /**
   * The URL to this draft transfer.
   */
  self: DraftTransferResponseSelf;
  /**
   * The URL to the documentation of this endpoint.
   */
  documentation?: DraftTransferResponseDocumentation | undefined;
};

export type DraftTransferResponse = {
  /**
   * Indicates the response contains a draft transfer object. Will always contain the string
   *
   * @remarks
   * `business-account-draft-transfer` for this endpoint.
   */
  resource: string;
  /**
   * The identifier uniquely referring to this draft transfer. Mollie assigns this identifier at draft transfer
   *
   * @remarks
   * creation time.
   */
  id: string;
  /**
   * Whether this entity was created in live mode or in test mode.
   */
  mode: Mode;
  /**
   * Whether the draft transfer was created via this API, or created in Mollie Apps.
   */
  source: DraftTransferResponseSource;
  /**
   * The debtor (sender) of the draft transfer, resolved from `debtorIban` at creation time.
   */
  debtor: DraftTransferResponseDebtor;
  /**
   * A party involved in the draft transfer, representing either the debtor (sender) or creditor
   *
   * @remarks
   * (recipient). Contains the party's name and account details.
   */
  creditor: DraftTransferParty;
  /**
   * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
   */
  amount: Amount;
  /**
   * A short description of the draft transfer. Once approved, this will appear on the bank statement of both
   *
   * @remarks
   * the debtor and creditor.
   */
  description?: string | null | undefined;
  /**
   * The date on which the resulting transfer will be executed, once approved. Defaults to same-day if omitted,
   *
   * @remarks
   * in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date format.
   */
  scheduledFor?: RFCDate | null | undefined;
  status: DraftTransferResponseStatus;
  /**
   * The reason for the current status. Only populated when `status` is `declined`, either free text provided
   *
   * @remarks
   * by the initiator or `"Declined by creator"` when cancelled via the `DELETE` endpoint.
   */
  statusReason?: string | null | undefined;
  /**
   * A chronological list of status transitions the draft transfer has gone through.
   */
  statusHistory: Array<DraftTransferStatusHistoryEntryResponse>;
  /**
   * The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  createdAt: string;
  /**
   * Links to related resources.
   */
  links: DraftTransferResponseLinks;
};

/** @internal */
export const DraftTransferResponseSource$inboundSchema: z.ZodType<
  DraftTransferResponseSource,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DraftTransferResponseSource);

/** @internal */
export const DraftTransferResponseAccount$inboundSchema: z.ZodType<
  DraftTransferResponseAccount,
  z.ZodTypeDef,
  unknown
> = z.object({
  iban: z.string(),
});

export function draftTransferResponseAccountFromJSON(
  jsonString: string,
): SafeParseResult<DraftTransferResponseAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DraftTransferResponseAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DraftTransferResponseAccount' from JSON`,
  );
}

/** @internal */
export const DraftTransferResponseDebtor$inboundSchema: z.ZodType<
  DraftTransferResponseDebtor,
  z.ZodTypeDef,
  unknown
> = z.object({
  fullName: z.string(),
  account: z.lazy(() => DraftTransferResponseAccount$inboundSchema),
});

export function draftTransferResponseDebtorFromJSON(
  jsonString: string,
): SafeParseResult<DraftTransferResponseDebtor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DraftTransferResponseDebtor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DraftTransferResponseDebtor' from JSON`,
  );
}

/** @internal */
export const DraftTransferResponseStatus$inboundSchema: z.ZodType<
  DraftTransferResponseStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DraftTransferResponseStatus);

/** @internal */
export const DraftTransferResponseSelf$inboundSchema: z.ZodType<
  DraftTransferResponseSelf,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
  type: z.string().optional(),
});

export function draftTransferResponseSelfFromJSON(
  jsonString: string,
): SafeParseResult<DraftTransferResponseSelf, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DraftTransferResponseSelf$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DraftTransferResponseSelf' from JSON`,
  );
}

/** @internal */
export const DraftTransferResponseDocumentation$inboundSchema: z.ZodType<
  DraftTransferResponseDocumentation,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
  type: z.string().optional(),
});

export function draftTransferResponseDocumentationFromJSON(
  jsonString: string,
): SafeParseResult<DraftTransferResponseDocumentation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DraftTransferResponseDocumentation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DraftTransferResponseDocumentation' from JSON`,
  );
}

/** @internal */
export const DraftTransferResponseLinks$inboundSchema: z.ZodType<
  DraftTransferResponseLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.lazy(() => DraftTransferResponseSelf$inboundSchema),
  documentation: z.lazy(() => DraftTransferResponseDocumentation$inboundSchema)
    .optional(),
});

export function draftTransferResponseLinksFromJSON(
  jsonString: string,
): SafeParseResult<DraftTransferResponseLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DraftTransferResponseLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DraftTransferResponseLinks' from JSON`,
  );
}

/** @internal */
export const DraftTransferResponse$inboundSchema: z.ZodType<
  DraftTransferResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource: z.string(),
  id: z.string(),
  mode: Mode$inboundSchema,
  source: DraftTransferResponseSource$inboundSchema,
  debtor: z.lazy(() => DraftTransferResponseDebtor$inboundSchema),
  creditor: DraftTransferParty$inboundSchema,
  amount: Amount$inboundSchema,
  description: z.nullable(z.string()).optional(),
  scheduledFor: z.nullable(z.string().transform(v => new RFCDate(v)))
    .optional(),
  status: DraftTransferResponseStatus$inboundSchema,
  statusReason: z.nullable(z.string()).optional(),
  statusHistory: z.array(DraftTransferStatusHistoryEntryResponse$inboundSchema),
  createdAt: z.string(),
  _links: z.lazy(() => DraftTransferResponseLinks$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

export function draftTransferResponseFromJSON(
  jsonString: string,
): SafeParseResult<DraftTransferResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DraftTransferResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DraftTransferResponse' from JSON`,
  );
}
