/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 39ed01c4877f
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Amount, Amount$inboundSchema } from "./amount.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  UnmatchedCreditTransferStatus,
  UnmatchedCreditTransferStatus$inboundSchema,
} from "./unmatchedcredittransferstatus.js";

/**
 * Details about the sender of the credit transfer.
 */
export type ListEntityUnmatchedCreditTransferSource = {
  /**
   * The format of the source account. Currently always `iban`.
   */
  format: string;
  /**
   * The name of the account holder who sent the unmatched credit transfer.
   */
  accountHolderName: string;
  /**
   * The IBAN of the sender's bank account.
   */
  iban: string;
  /**
   * The BIC of the sender's bank.
   */
  bic: string;
};

/**
 * Structured references provided with the unmatched credit transfer.
 */
export type ListEntityUnmatchedCreditTransferReferences = {
  /**
   * The creditor reference.
   */
  creditorReference?: string | null | undefined;
  /**
   * The end-to-end identifier.
   */
  endToEndId?: string | undefined;
};

/**
 * Remittance information provided with the unmatched credit transfer.
 */
export type ListEntityUnmatchedCreditTransferRemittanceInformation = {
  /**
   * Unstructured remittance information, such as a free-text payment description.
   */
  unstructured?: string | undefined;
  /**
   * Structured references provided with the unmatched credit transfer.
   */
  references?: ListEntityUnmatchedCreditTransferReferences | undefined;
};

/**
 * The URL to this unmatched credit transfer.
 */
export type ListEntityUnmatchedCreditTransferSelf = {
  href?: string | undefined;
  type?: string | undefined;
};

/**
 * Links to related resources.
 */
export type ListEntityUnmatchedCreditTransferLinks = {
  /**
   * The URL to this unmatched credit transfer.
   */
  self?: ListEntityUnmatchedCreditTransferSelf | undefined;
};

export type ListEntityUnmatchedCreditTransfer = {
  /**
   * Indicates the response contains an unmatched credit transfer object. Will always contain the string
   *
   * @remarks
   * `unmatched-credit-transfer` for this endpoint.
   */
  resource: string;
  /**
   * The identifier uniquely referring to this unmatched credit transfer.
   */
  id: string;
  profileId: string;
  /**
   * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
   */
  amount: Amount;
  /**
   * Details about the sender of the credit transfer.
   */
  source: ListEntityUnmatchedCreditTransferSource;
  /**
   * Remittance information provided with the unmatched credit transfer.
   */
  remittanceInformation: ListEntityUnmatchedCreditTransferRemittanceInformation;
  status: UnmatchedCreditTransferStatus;
  /**
   * The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  createdAt: string;
  /**
   * The date and time at which the unmatched credit transfer expires, in
   *
   * @remarks
   * [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  expiresAt: string;
  /**
   * The IDs of the payments this credit transfer was matched to. Only present when the status is `matched`.
   */
  paymentIds?: Array<string> | undefined;
  /**
   * Links to related resources.
   */
  links: ListEntityUnmatchedCreditTransferLinks;
};

/** @internal */
export const ListEntityUnmatchedCreditTransferSource$inboundSchema: z.ZodType<
  ListEntityUnmatchedCreditTransferSource,
  z.ZodTypeDef,
  unknown
> = z.object({
  format: z.string(),
  accountHolderName: z.string(),
  iban: z.string(),
  bic: z.string(),
});

export function listEntityUnmatchedCreditTransferSourceFromJSON(
  jsonString: string,
): SafeParseResult<
  ListEntityUnmatchedCreditTransferSource,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListEntityUnmatchedCreditTransferSource$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListEntityUnmatchedCreditTransferSource' from JSON`,
  );
}

/** @internal */
export const ListEntityUnmatchedCreditTransferReferences$inboundSchema:
  z.ZodType<
    ListEntityUnmatchedCreditTransferReferences,
    z.ZodTypeDef,
    unknown
  > = z.object({
    creditorReference: z.nullable(z.string()).optional(),
    endToEndId: z.string().optional(),
  });

export function listEntityUnmatchedCreditTransferReferencesFromJSON(
  jsonString: string,
): SafeParseResult<
  ListEntityUnmatchedCreditTransferReferences,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListEntityUnmatchedCreditTransferReferences$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListEntityUnmatchedCreditTransferReferences' from JSON`,
  );
}

/** @internal */
export const ListEntityUnmatchedCreditTransferRemittanceInformation$inboundSchema:
  z.ZodType<
    ListEntityUnmatchedCreditTransferRemittanceInformation,
    z.ZodTypeDef,
    unknown
  > = z.object({
    unstructured: z.string().optional(),
    references: z.lazy(() =>
      ListEntityUnmatchedCreditTransferReferences$inboundSchema
    ).optional(),
  });

export function listEntityUnmatchedCreditTransferRemittanceInformationFromJSON(
  jsonString: string,
): SafeParseResult<
  ListEntityUnmatchedCreditTransferRemittanceInformation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListEntityUnmatchedCreditTransferRemittanceInformation$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ListEntityUnmatchedCreditTransferRemittanceInformation' from JSON`,
  );
}

/** @internal */
export const ListEntityUnmatchedCreditTransferSelf$inboundSchema: z.ZodType<
  ListEntityUnmatchedCreditTransferSelf,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
  type: z.string().optional(),
});

export function listEntityUnmatchedCreditTransferSelfFromJSON(
  jsonString: string,
): SafeParseResult<ListEntityUnmatchedCreditTransferSelf, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListEntityUnmatchedCreditTransferSelf$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntityUnmatchedCreditTransferSelf' from JSON`,
  );
}

/** @internal */
export const ListEntityUnmatchedCreditTransferLinks$inboundSchema: z.ZodType<
  ListEntityUnmatchedCreditTransferLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: z.lazy(() => ListEntityUnmatchedCreditTransferSelf$inboundSchema)
    .optional(),
});

export function listEntityUnmatchedCreditTransferLinksFromJSON(
  jsonString: string,
): SafeParseResult<ListEntityUnmatchedCreditTransferLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListEntityUnmatchedCreditTransferLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntityUnmatchedCreditTransferLinks' from JSON`,
  );
}

/** @internal */
export const ListEntityUnmatchedCreditTransfer$inboundSchema: z.ZodType<
  ListEntityUnmatchedCreditTransfer,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource: z.string(),
  id: z.string(),
  profileId: z.string(),
  amount: Amount$inboundSchema,
  source: z.lazy(() => ListEntityUnmatchedCreditTransferSource$inboundSchema),
  remittanceInformation: z.lazy(() =>
    ListEntityUnmatchedCreditTransferRemittanceInformation$inboundSchema
  ),
  status: UnmatchedCreditTransferStatus$inboundSchema,
  createdAt: z.string(),
  expiresAt: z.string(),
  paymentIds: z.array(z.string()).optional(),
  _links: z.lazy(() => ListEntityUnmatchedCreditTransferLinks$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

export function listEntityUnmatchedCreditTransferFromJSON(
  jsonString: string,
): SafeParseResult<ListEntityUnmatchedCreditTransfer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntityUnmatchedCreditTransfer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntityUnmatchedCreditTransfer' from JSON`,
  );
}
