/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Mode, Mode$inboundSchema, Mode$outboundSchema } from "./mode.js";
import {
  TerminalBrand,
  TerminalBrand$inboundSchema,
  TerminalBrand$outboundSchema,
} from "./terminalbrand.js";
import {
  TerminalModel,
  TerminalModel$inboundSchema,
  TerminalModel$outboundSchema,
} from "./terminalmodel.js";
import {
  Url,
  Url$inboundSchema,
  Url$Outbound,
  Url$outboundSchema,
} from "./url.js";

/**
 * The status of the terminal.
 */
export const ListEntityTerminalStatus = {
  Pending: "pending",
  Active: "active",
  Inactive: "inactive",
} as const;
/**
 * The status of the terminal.
 */
export type ListEntityTerminalStatus = OpenEnum<
  typeof ListEntityTerminalStatus
>;

/**
 * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
 */
export type ListEntityTerminalLinks = {
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  self: Url;
};

export type ListEntityTerminal = {
  /**
   * Indicates the response contains a terminal object. Will always contain the string `terminal` for this endpoint.
   */
  resource: string;
  /**
   * The identifier uniquely referring to this terminal. Example: `term_7MgL4wea46qkRcoTZjWEH`.
   */
  id: string;
  /**
   * Whether this entity was created in live mode or in test mode.
   */
  mode: Mode;
  /**
   * A short description of the terminal. The description can be used as an identifier for the terminal. Currently, the
   *
   * @remarks
   * description is set when the terminal is initially configured. It will be visible in the Mollie Dashboard, and it
   * may be visible on the device itself depending on the device.
   */
  description: string;
  status: ListEntityTerminalStatus;
  /**
   * The brand of the terminal.
   */
  brand: TerminalBrand | null;
  /**
   * The model of the terminal. For example for a PAX A920, this field's value will be `A920`.
   */
  model: TerminalModel | null;
  /**
   * The serial number of the terminal. The serial number is provided at terminal creation time.
   */
  serialNumber: string | null;
  /**
   * The currency configured on the terminal, in ISO 4217 format. Currently most of our terminals are bound to a
   *
   * @remarks
   * specific currency, chosen during setup.
   */
  currency: string;
  /**
   * The identifier referring to the [profile](get-profile) this entity belongs to.
   *
   * @remarks
   *
   * Most API credentials are linked to a single profile. In these cases the `profileId` can be omitted in the creation
   * request. For organization-level credentials such as OAuth access tokens however, the `profileId` parameter is
   * required.
   */
  profileId: string;
  /**
   * The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  createdAt: string;
  /**
   * The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  updatedAt: string;
  /**
   * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
   */
  links: ListEntityTerminalLinks;
};

/** @internal */
export const ListEntityTerminalStatus$inboundSchema: z.ZodType<
  ListEntityTerminalStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ListEntityTerminalStatus);
/** @internal */
export const ListEntityTerminalStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ListEntityTerminalStatus
> = openEnums.outboundSchema(ListEntityTerminalStatus);

/** @internal */
export const ListEntityTerminalLinks$inboundSchema: z.ZodType<
  ListEntityTerminalLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: Url$inboundSchema,
});
/** @internal */
export type ListEntityTerminalLinks$Outbound = {
  self: Url$Outbound;
};

/** @internal */
export const ListEntityTerminalLinks$outboundSchema: z.ZodType<
  ListEntityTerminalLinks$Outbound,
  z.ZodTypeDef,
  ListEntityTerminalLinks
> = z.object({
  self: Url$outboundSchema,
});

export function listEntityTerminalLinksToJSON(
  listEntityTerminalLinks: ListEntityTerminalLinks,
): string {
  return JSON.stringify(
    ListEntityTerminalLinks$outboundSchema.parse(listEntityTerminalLinks),
  );
}
export function listEntityTerminalLinksFromJSON(
  jsonString: string,
): SafeParseResult<ListEntityTerminalLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntityTerminalLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntityTerminalLinks' from JSON`,
  );
}

/** @internal */
export const ListEntityTerminal$inboundSchema: z.ZodType<
  ListEntityTerminal,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource: z.string(),
  id: z.string(),
  mode: Mode$inboundSchema,
  description: z.string(),
  status: ListEntityTerminalStatus$inboundSchema,
  brand: z.nullable(TerminalBrand$inboundSchema),
  model: z.nullable(TerminalModel$inboundSchema),
  serialNumber: z.nullable(z.string()),
  currency: z.string(),
  profileId: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  _links: z.lazy(() => ListEntityTerminalLinks$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});
/** @internal */
export type ListEntityTerminal$Outbound = {
  resource: string;
  id: string;
  mode: string;
  description: string;
  status: string;
  brand: string | null;
  model: string | null;
  serialNumber: string | null;
  currency: string;
  profileId: string;
  createdAt: string;
  updatedAt: string;
  _links: ListEntityTerminalLinks$Outbound;
};

/** @internal */
export const ListEntityTerminal$outboundSchema: z.ZodType<
  ListEntityTerminal$Outbound,
  z.ZodTypeDef,
  ListEntityTerminal
> = z.object({
  resource: z.string(),
  id: z.string(),
  mode: Mode$outboundSchema,
  description: z.string(),
  status: ListEntityTerminalStatus$outboundSchema,
  brand: z.nullable(TerminalBrand$outboundSchema),
  model: z.nullable(TerminalModel$outboundSchema),
  serialNumber: z.nullable(z.string()),
  currency: z.string(),
  profileId: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  links: z.lazy(() => ListEntityTerminalLinks$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    links: "_links",
  });
});

export function listEntityTerminalToJSON(
  listEntityTerminal: ListEntityTerminal,
): string {
  return JSON.stringify(
    ListEntityTerminal$outboundSchema.parse(listEntityTerminal),
  );
}
export function listEntityTerminalFromJSON(
  jsonString: string,
): SafeParseResult<ListEntityTerminal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntityTerminal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntityTerminal' from JSON`,
  );
}
