/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 399cfa2bf973
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const OpenSettlementId = {
  Open: "open",
} as const;
export type OpenSettlementId = OpenEnum<typeof OpenSettlementId>;

/** @internal */
export const OpenSettlementId$inboundSchema: z.ZodType<
  OpenSettlementId,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(OpenSettlementId);
