/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../types/enums.js";

export const PaymentLinkSequenceTypeResponse = {
  Oneoff: "oneoff",
  First: "first",
} as const;
export type PaymentLinkSequenceTypeResponse = OpenEnum<
  typeof PaymentLinkSequenceTypeResponse
>;

/** @internal */
export const PaymentLinkSequenceTypeResponse$inboundSchema: z.ZodType<
  PaymentLinkSequenceTypeResponse,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(PaymentLinkSequenceTypeResponse),
    z.string().transform(catchUnrecognizedEnum),
  ]);
/** @internal */
export const PaymentLinkSequenceTypeResponse$outboundSchema: z.ZodType<
  PaymentLinkSequenceTypeResponse,
  z.ZodTypeDef,
  PaymentLinkSequenceTypeResponse
> = z.union([
  z.nativeEnum(PaymentLinkSequenceTypeResponse),
  z.string().and(z.custom<Unrecognized<string>>()),
]);
