/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * The method used to verify the cardholder's identity.
 */
export const PaymentDetailsReceiptCardVerificationMethodResponse = {
  NoCvmRequired: "no-cvm-required",
  OnlinePin: "online-pin",
  OfflinePin: "offline-pin",
  ConsumerDevice: "consumer-device",
  Signature: "signature",
  SignatureAndOnlinePin: "signature-and-online-pin",
  OnlinePinAndSignature: "online-pin-and-signature",
  None: "none",
  Failed: "failed",
} as const;
/**
 * The method used to verify the cardholder's identity.
 */
export type PaymentDetailsReceiptCardVerificationMethodResponse = OpenEnum<
  typeof PaymentDetailsReceiptCardVerificationMethodResponse
>;

/** @internal */
export const PaymentDetailsReceiptCardVerificationMethodResponse$inboundSchema:
  z.ZodType<
    PaymentDetailsReceiptCardVerificationMethodResponse,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(
    PaymentDetailsReceiptCardVerificationMethodResponse,
  );
/** @internal */
export const PaymentDetailsReceiptCardVerificationMethodResponse$outboundSchema:
  z.ZodType<
    string,
    z.ZodTypeDef,
    PaymentDetailsReceiptCardVerificationMethodResponse
  > = openEnums.outboundSchema(
    PaymentDetailsReceiptCardVerificationMethodResponse,
  );
