/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  SalesInvoiceRecipientLocaleResponse,
  SalesInvoiceRecipientLocaleResponse$inboundSchema,
  SalesInvoiceRecipientLocaleResponse$outboundSchema,
} from "./salesinvoicerecipientlocaleresponse.js";
import {
  SalesInvoiceRecipientTypeResponse,
  SalesInvoiceRecipientTypeResponse$inboundSchema,
  SalesInvoiceRecipientTypeResponse$outboundSchema,
} from "./salesinvoicerecipienttyperesponse.js";

export type SalesInvoiceRecipientResponse = {
  /**
   * The type of recipient, either `consumer` or `business`. This will determine what further fields are
   *
   * @remarks
   * required on the `recipient` object.
   */
  type: SalesInvoiceRecipientTypeResponse;
  /**
   * The title of the `consumer` type recipient, for example Mr. or Mrs..
   */
  title?: string | null | undefined;
  /**
   * The given name (first name) of the `consumer` type recipient should be at least two characters and cannot contain
   *
   * @remarks
   * only numbers.
   */
  givenName?: string | null | undefined;
  /**
   * The given name (last name) of the `consumer` type recipient should be at least two characters and cannot contain
   *
   * @remarks
   * only numbers.
   */
  familyName?: string | null | undefined;
  /**
   * The trading name of the `business` type recipient.
   */
  organizationName?: string | null | undefined;
  /**
   * The Chamber of Commerce number of the organization for a `business` type recipient. Either this or `vatNumber`
   *
   * @remarks
   * has to be provided.
   */
  organizationNumber?: string | null | undefined;
  /**
   * The VAT number of the organization for a `business` type recipient. Either this or `organizationNumber`
   *
   * @remarks
   * has to be provided.
   */
  vatNumber?: string | null | undefined;
  /**
   * The email address of the recipient.
   */
  email: string;
  /**
   * The phone number of the recipient.
   */
  phone?: string | null | undefined;
  /**
   * A street and street number.
   */
  streetAndNumber: string;
  /**
   * Any additional addressing details, for example an apartment number.
   */
  streetAdditional?: string | null | undefined;
  /**
   * A postal code.
   */
  postalCode: string;
  /**
   * The recipient's city.
   */
  city: string;
  /**
   * The recipient's region.
   */
  region?: string | null | undefined;
  /**
   * A country code in [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) format.
   */
  country: string;
  /**
   * The locale for the recipient, to be used for translations in PDF generation and payment pages.
   */
  locale: SalesInvoiceRecipientLocaleResponse;
};

/** @internal */
export const SalesInvoiceRecipientResponse$inboundSchema: z.ZodType<
  SalesInvoiceRecipientResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: SalesInvoiceRecipientTypeResponse$inboundSchema,
  title: z.nullable(z.string()).optional(),
  givenName: z.nullable(z.string()).optional(),
  familyName: z.nullable(z.string()).optional(),
  organizationName: z.nullable(z.string()).optional(),
  organizationNumber: z.nullable(z.string()).optional(),
  vatNumber: z.nullable(z.string()).optional(),
  email: z.string(),
  phone: z.nullable(z.string()).optional(),
  streetAndNumber: z.string(),
  streetAdditional: z.nullable(z.string()).optional(),
  postalCode: z.string(),
  city: z.string(),
  region: z.nullable(z.string()).optional(),
  country: z.string(),
  locale: SalesInvoiceRecipientLocaleResponse$inboundSchema,
});
/** @internal */
export type SalesInvoiceRecipientResponse$Outbound = {
  type: string;
  title?: string | null | undefined;
  givenName?: string | null | undefined;
  familyName?: string | null | undefined;
  organizationName?: string | null | undefined;
  organizationNumber?: string | null | undefined;
  vatNumber?: string | null | undefined;
  email: string;
  phone?: string | null | undefined;
  streetAndNumber: string;
  streetAdditional?: string | null | undefined;
  postalCode: string;
  city: string;
  region?: string | null | undefined;
  country: string;
  locale: string;
};

/** @internal */
export const SalesInvoiceRecipientResponse$outboundSchema: z.ZodType<
  SalesInvoiceRecipientResponse$Outbound,
  z.ZodTypeDef,
  SalesInvoiceRecipientResponse
> = z.object({
  type: SalesInvoiceRecipientTypeResponse$outboundSchema,
  title: z.nullable(z.string()).optional(),
  givenName: z.nullable(z.string()).optional(),
  familyName: z.nullable(z.string()).optional(),
  organizationName: z.nullable(z.string()).optional(),
  organizationNumber: z.nullable(z.string()).optional(),
  vatNumber: z.nullable(z.string()).optional(),
  email: z.string(),
  phone: z.nullable(z.string()).optional(),
  streetAndNumber: z.string(),
  streetAdditional: z.nullable(z.string()).optional(),
  postalCode: z.string(),
  city: z.string(),
  region: z.nullable(z.string()).optional(),
  country: z.string(),
  locale: SalesInvoiceRecipientLocaleResponse$outboundSchema,
});

export function salesInvoiceRecipientResponseToJSON(
  salesInvoiceRecipientResponse: SalesInvoiceRecipientResponse,
): string {
  return JSON.stringify(
    SalesInvoiceRecipientResponse$outboundSchema.parse(
      salesInvoiceRecipientResponse,
    ),
  );
}
export function salesInvoiceRecipientResponseFromJSON(
  jsonString: string,
): SafeParseResult<SalesInvoiceRecipientResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SalesInvoiceRecipientResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SalesInvoiceRecipientResponse' from JSON`,
  );
}
