/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * The VAT scheme to create the invoice for. You must be enrolled with One Stop Shop enabled to use it.
 */
export const SalesInvoiceVatSchemeResponse = {
  Standard: "standard",
  OneStopShop: "one-stop-shop",
} as const;
/**
 * The VAT scheme to create the invoice for. You must be enrolled with One Stop Shop enabled to use it.
 */
export type SalesInvoiceVatSchemeResponse = OpenEnum<
  typeof SalesInvoiceVatSchemeResponse
>;

/** @internal */
export const SalesInvoiceVatSchemeResponse$inboundSchema: z.ZodType<
  SalesInvoiceVatSchemeResponse,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SalesInvoiceVatSchemeResponse);
/** @internal */
export const SalesInvoiceVatSchemeResponse$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  SalesInvoiceVatSchemeResponse
> = openEnums.outboundSchema(SalesInvoiceVatSchemeResponse);
