/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../types/enums.js";

/**
 * The way through which the invoice is to be set to paid.
 */
export const SalesInvoicePaymentDetailsSourceResponse = {
  Manual: "manual",
  PaymentLink: "payment-link",
  Payment: "payment",
} as const;
/**
 * The way through which the invoice is to be set to paid.
 */
export type SalesInvoicePaymentDetailsSourceResponse = OpenEnum<
  typeof SalesInvoicePaymentDetailsSourceResponse
>;

/** @internal */
export const SalesInvoicePaymentDetailsSourceResponse$inboundSchema: z.ZodType<
  SalesInvoicePaymentDetailsSourceResponse,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(SalesInvoicePaymentDetailsSourceResponse),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const SalesInvoicePaymentDetailsSourceResponse$outboundSchema: z.ZodType<
  SalesInvoicePaymentDetailsSourceResponse,
  z.ZodTypeDef,
  SalesInvoicePaymentDetailsSourceResponse
> = z.union([
  z.nativeEnum(SalesInvoicePaymentDetailsSourceResponse),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SalesInvoicePaymentDetailsSourceResponse$ {
  /** @deprecated use `SalesInvoicePaymentDetailsSourceResponse$inboundSchema` instead. */
  export const inboundSchema =
    SalesInvoicePaymentDetailsSourceResponse$inboundSchema;
  /** @deprecated use `SalesInvoicePaymentDetailsSourceResponse$outboundSchema` instead. */
  export const outboundSchema =
    SalesInvoicePaymentDetailsSourceResponse$outboundSchema;
}
