/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 58048b006ac9
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Url, Url$inboundSchema } from "./url.js";

/**
 * An object with several relevant URLs. Every URL object will contain an `href` and a `type` field.
 *
 * @remarks
 *
 * This endpoint always points to your organization's current open or next settlement rather than one specific
 * settlement, so it doesn't return links to that settlement's payments, captures, refunds, chargebacks, or invoice.
 */
export type SettlementConvenienceLinks = {
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  self: Url;
  /**
   * In v2 endpoints, URLs are commonly represented as objects with an `href` and `type` field.
   */
  documentation?: Url | undefined;
};

/** @internal */
export const SettlementConvenienceLinks$inboundSchema: z.ZodType<
  SettlementConvenienceLinks,
  z.ZodTypeDef,
  unknown
> = z.object({
  self: Url$inboundSchema,
  documentation: Url$inboundSchema.optional(),
});

export function settlementConvenienceLinksFromJSON(
  jsonString: string,
): SafeParseResult<SettlementConvenienceLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettlementConvenienceLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettlementConvenienceLinks' from JSON`,
  );
}
