/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f293b6ef2c8f
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AfterBalance,
  AfterBalance$inboundSchema,
  AfterBalance$Outbound,
  AfterBalance$outboundSchema,
} from "./afterbalance.js";
import {
  Amount,
  Amount$inboundSchema,
  Amount$Outbound,
  Amount$outboundSchema,
} from "./amount.js";
import {
  Counterparty,
  Counterparty$inboundSchema,
  Counterparty$Outbound,
  Counterparty$outboundSchema,
} from "./counterparty.js";
import {
  CreditDebitIndicator,
  CreditDebitIndicator$inboundSchema,
  CreditDebitIndicator$outboundSchema,
} from "./creditdebitindicator.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Mode, Mode$inboundSchema, Mode$outboundSchema } from "./mode.js";
import {
  TransactionType,
  TransactionType$inboundSchema,
  TransactionType$outboundSchema,
} from "./transactiontype.js";

export type TransactionResponse = {
  /**
   * Indicates the response contains a business account transaction object. Will always contain the string
   *
   * @remarks
   * `business-account-transaction` for this endpoint.
   */
  resource: string;
  /**
   * The identifier uniquely referring to this transaction. Mollie assigns this identifier at transaction creation
   *
   * @remarks
   * time.
   */
  id: string;
  /**
   * The identifier of the business account this transaction belongs to.
   */
  businessAccountId: string;
  /**
   * Indicates whether the entry is a credit or debit from the perspective of the account holder.
   */
  creditDebitIndicator: CreditDebitIndicator;
  /**
   * Indicates what kind of transaction this is.
   *
   * @remarks
   *
   * We may introduce new transaction types as we expand the product. We recommend building your integration
   * to handle unexpected values gracefully, so nothing breaks when that happens.
   */
  type: TransactionType;
  /**
   * In v2 endpoints, monetary amounts are represented as objects with a `currency` and `value` field.
   */
  amount: Amount;
  /**
   * A short description of the transaction.
   */
  description?: string | null | undefined;
  /**
   * The counterparty involved in the transaction, including their name and account identifier.
   */
  counterparty?: Counterparty | undefined;
  /**
   * The balance of the business account after this transaction was processed.
   */
  afterBalance?: AfterBalance | undefined;
  /**
   * The date and time when the transaction was processed, in ISO 8601 format.
   */
  processedAt?: string | null | undefined;
  /**
   * Whether this entity was created in live mode or in test mode.
   */
  mode: Mode;
  /**
   * The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  createdAt: string;
};

/** @internal */
export const TransactionResponse$inboundSchema: z.ZodType<
  TransactionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource: z.string(),
  id: z.string(),
  businessAccountId: z.string(),
  creditDebitIndicator: CreditDebitIndicator$inboundSchema,
  type: TransactionType$inboundSchema,
  amount: Amount$inboundSchema,
  description: z.nullable(z.string()).optional(),
  counterparty: Counterparty$inboundSchema.optional(),
  afterBalance: AfterBalance$inboundSchema.optional(),
  processedAt: z.nullable(z.string()).optional(),
  mode: Mode$inboundSchema,
  createdAt: z.string(),
});
/** @internal */
export type TransactionResponse$Outbound = {
  resource: string;
  id: string;
  businessAccountId: string;
  creditDebitIndicator: string;
  type: string;
  amount: Amount$Outbound;
  description?: string | null | undefined;
  counterparty?: Counterparty$Outbound | undefined;
  afterBalance?: AfterBalance$Outbound | undefined;
  processedAt?: string | null | undefined;
  mode: string;
  createdAt: string;
};

/** @internal */
export const TransactionResponse$outboundSchema: z.ZodType<
  TransactionResponse$Outbound,
  z.ZodTypeDef,
  TransactionResponse
> = z.object({
  resource: z.string(),
  id: z.string(),
  businessAccountId: z.string(),
  creditDebitIndicator: CreditDebitIndicator$outboundSchema,
  type: TransactionType$outboundSchema,
  amount: Amount$outboundSchema,
  description: z.nullable(z.string()).optional(),
  counterparty: Counterparty$outboundSchema.optional(),
  afterBalance: AfterBalance$outboundSchema.optional(),
  processedAt: z.nullable(z.string()).optional(),
  mode: Mode$outboundSchema,
  createdAt: z.string(),
});

export function transactionResponseToJSON(
  transactionResponse: TransactionResponse,
): string {
  return JSON.stringify(
    TransactionResponse$outboundSchema.parse(transactionResponse),
  );
}
export function transactionResponseFromJSON(
  jsonString: string,
): SafeParseResult<TransactionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionResponse' from JSON`,
  );
}
