/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 70f9c8054155
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The action performed on the unmatched credit transfer.
 */
export const Action = {
  Match: "match",
  Return: "return",
} as const;
/**
 * The action performed on the unmatched credit transfer.
 */
export type Action = OpenEnum<typeof Action>;

/**
 * The current status of the action.
 */
export const UnmatchedCreditTransferActionResponseStatus = {
  Pending: "pending",
} as const;
/**
 * The current status of the action.
 */
export type UnmatchedCreditTransferActionResponseStatus = OpenEnum<
  typeof UnmatchedCreditTransferActionResponseStatus
>;

/**
 * Additional details about the action.
 */
export type UnmatchedCreditTransferActionResponseDetails = {
  /**
   * The IDs of the payments matched to the unmatched credit transfer.
   */
  paymentIds?: Array<string> | undefined;
};

/**
 * The URL to this action.
 */
export type UnmatchedCreditTransferActionResponseSelf = {
  href?: string | undefined;
  type?: string | undefined;
};

/**
 * The URL to the documentation of this endpoint.
 */
export type UnmatchedCreditTransferActionResponseDocumentation = {
  href?: string | undefined;
  type?: string | undefined;
};

/**
 * Links to related resources.
 */
export type UnmatchedCreditTransferActionResponseLinks = {
  /**
   * The URL to this action.
   */
  self?: UnmatchedCreditTransferActionResponseSelf | undefined;
  /**
   * The URL to the documentation of this endpoint.
   */
  documentation?:
    | UnmatchedCreditTransferActionResponseDocumentation
    | undefined;
};

export type UnmatchedCreditTransferActionResponse = {
  /**
   * The resource type of the object.
   */
  resource: string;
  /**
   * The identifier uniquely referring to this unmatched credit transfer action.
   */
  id: string;
  /**
   * The identifier of the unmatched credit transfer this action belongs to.
   */
  unmatchedCreditTransferId: string;
  /**
   * The action performed on the unmatched credit transfer.
   */
  action: Action;
  /**
   * The current status of the action.
   */
  status: UnmatchedCreditTransferActionResponseStatus;
  /**
   * The entity's date and time of creation, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
   */
  createdAt: string;
  /**
   * Additional details about the action.
   */
  details?: UnmatchedCreditTransferActionResponseDetails | undefined;
  /**
   * Links to related resources.
   */
  links: UnmatchedCreditTransferActionResponseLinks;
};

/** @internal */
export const Action$inboundSchema: z.ZodType<Action, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(Action);

/** @internal */
export const UnmatchedCreditTransferActionResponseStatus$inboundSchema:
  z.ZodType<
    UnmatchedCreditTransferActionResponseStatus,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(UnmatchedCreditTransferActionResponseStatus);

/** @internal */
export const UnmatchedCreditTransferActionResponseDetails$inboundSchema:
  z.ZodType<
    UnmatchedCreditTransferActionResponseDetails,
    z.ZodTypeDef,
    unknown
  > = z.object({
    paymentIds: z.array(z.string()).optional(),
  });

export function unmatchedCreditTransferActionResponseDetailsFromJSON(
  jsonString: string,
): SafeParseResult<
  UnmatchedCreditTransferActionResponseDetails,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UnmatchedCreditTransferActionResponseDetails$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UnmatchedCreditTransferActionResponseDetails' from JSON`,
  );
}

/** @internal */
export const UnmatchedCreditTransferActionResponseSelf$inboundSchema: z.ZodType<
  UnmatchedCreditTransferActionResponseSelf,
  z.ZodTypeDef,
  unknown
> = z.object({
  href: z.string().optional(),
  type: z.string().optional(),
});

export function unmatchedCreditTransferActionResponseSelfFromJSON(
  jsonString: string,
): SafeParseResult<
  UnmatchedCreditTransferActionResponseSelf,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UnmatchedCreditTransferActionResponseSelf$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UnmatchedCreditTransferActionResponseSelf' from JSON`,
  );
}

/** @internal */
export const UnmatchedCreditTransferActionResponseDocumentation$inboundSchema:
  z.ZodType<
    UnmatchedCreditTransferActionResponseDocumentation,
    z.ZodTypeDef,
    unknown
  > = z.object({
    href: z.string().optional(),
    type: z.string().optional(),
  });

export function unmatchedCreditTransferActionResponseDocumentationFromJSON(
  jsonString: string,
): SafeParseResult<
  UnmatchedCreditTransferActionResponseDocumentation,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UnmatchedCreditTransferActionResponseDocumentation$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UnmatchedCreditTransferActionResponseDocumentation' from JSON`,
  );
}

/** @internal */
export const UnmatchedCreditTransferActionResponseLinks$inboundSchema:
  z.ZodType<UnmatchedCreditTransferActionResponseLinks, z.ZodTypeDef, unknown> =
    z.object({
      self: z.lazy(() =>
        UnmatchedCreditTransferActionResponseSelf$inboundSchema
      ).optional(),
      documentation: z.lazy(() =>
        UnmatchedCreditTransferActionResponseDocumentation$inboundSchema
      ).optional(),
    });

export function unmatchedCreditTransferActionResponseLinksFromJSON(
  jsonString: string,
): SafeParseResult<
  UnmatchedCreditTransferActionResponseLinks,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UnmatchedCreditTransferActionResponseLinks$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UnmatchedCreditTransferActionResponseLinks' from JSON`,
  );
}

/** @internal */
export const UnmatchedCreditTransferActionResponse$inboundSchema: z.ZodType<
  UnmatchedCreditTransferActionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource: z.string(),
  id: z.string(),
  unmatchedCreditTransferId: z.string(),
  action: Action$inboundSchema,
  status: UnmatchedCreditTransferActionResponseStatus$inboundSchema,
  createdAt: z.string(),
  details: z.lazy(() =>
    UnmatchedCreditTransferActionResponseDetails$inboundSchema
  ).optional(),
  _links: z.lazy(() =>
    UnmatchedCreditTransferActionResponseLinks$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "_links": "links",
  });
});

export function unmatchedCreditTransferActionResponseFromJSON(
  jsonString: string,
): SafeParseResult<UnmatchedCreditTransferActionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UnmatchedCreditTransferActionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnmatchedCreditTransferActionResponse' from JSON`,
  );
}
