name: Publish
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Commit SHA to generate release notes for
        type: string
        required: false
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    with:
      target: client
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

  trigger-release-note:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Note workflow
        run: |
          curl -sf -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/sdk_release_note.yaml/dispatches" \
            -d "{\"ref\":\"main\",\"inputs\":{\"commit_sha\":\"${{ inputs.commit_sha || github.sha }}\"}}"
